openapi: 3.0.0
info:
  title: SPV Wallet API
  version: main
  license:
    name: MIT
    url: https://github.com/bitcoin-sv/spv-wallet/blob/main/LICENSE

components:
  securitySchemes:
    XPubAuth:
      type: apiKey
      in: header
      name: x-auth-xpub
      description: "Authentication using x-auth-xpub header"
