# Basic dependabot.yml to update gomod, Github Actions and Docker
version: 2
updates:
  # Maintain dependencies for the core library
  - package-ecosystem: "gomod"
    target-branch: "main"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
    open-pull-requests-limit: 10

  - package-ecosystem: "gomod"
    target-branch: "main"
    directory: "/engine"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
    open-pull-requests-limit: 10

  - package-ecosystem: "gomod"
    target-branch: "main"
    directory: "/models"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
    open-pull-requests-limit: 10

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    target-branch: "main"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
    open-pull-requests-limit: 10

  # Maintain dependencies for Docker
  - package-ecosystem: "docker"
    target-branch: "main"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
    open-pull-requests-limit: 10

  # Maintain dependencies for Docker
  - package-ecosystem: "docker"
    target-branch: "main"
    directory: "/release"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
    open-pull-requests-limit: 10
