openapi: 3.0.0
info:
  title: ignored
  version: ignored

components:
  schemas:
    Schema:
      type: object
      properties:
        code:
          type: string
          description: Error code
        message:
          type: string
          description: Error message
      required:
        - code
        - message
      additionalProperties: false

    Unauthorized:
      oneOf:
        - $ref: '#/components/schemas/Authorization'
        - $ref: '#/components/schemas/AdminAuthOnNonAdminEndpoint'
        - $ref: '#/components/schemas/UserAuthOnNonUserEndpoint'
        - $ref: '#/components/schemas/ErrXPubAuthRequired'

    Authorization:
      allOf:
        - $ref: '#/components/schemas/Schema'
        - type: object
          properties:
            code:
              example: "error-unauthorized"
            message:
              example: "unauthorized"

    AdminAuthOnNonAdminEndpoint:
      allOf:
        - $ref: '#/components/schemas/Schema'
        - type: object
          properties:
            code:
              example: "error-admin-auth-on-non-admin-endpoint"
            message:
              example: "cannot call non-admin endpoints with admin authorization"

    UserAuthOnNonUserEndpoint:
      allOf:
        - $ref: '#/components/schemas/Schema'
        - type: object
          properties:
            code:
              example: "error-user-auth-on-non-user-endpoint"
            message:
              example: "cannot call non-user endpoints with user authorization"

    ErrXPubAuthRequired:
      allOf:
        - $ref: '#/components/schemas/Schema'
        - type: object
          properties:
            code:
              example: "error-xpub-authorization-required"
            message:
              example: "xpub authorization required"

    ErrCannotParseQueryParams:
      allOf:
        - $ref: '#/components/schemas/Schema'
        - type: object
          properties:
            code:
              example: "error-query-params-invalid"
            message:
              example: "cannot parse request query params"

    CannotBindRequest:
      allOf:
        - $ref: '#/components/schemas/Schema'
        - type: object
          properties:
            code:
              example: "error-bind-body-invalid"
            message:
              example: "cannot bind request body"

    ErrInternal:
      allOf:
        - $ref: '#/components/schemas/Schema'
        - type: object
          properties:
            code:
              example: "error-internal-server-error"
            message:
              example: "internal server error"

    ErrInvalidDataID:
      allOf:
        - $ref: '#/components/schemas/Schema'
        - type: object
          properties:
            code:
              example: "error-invalid-data-id"
            message:
              example: "invalid data id"

    ErrDataNotFound:
      allOf:
        - $ref: '#/components/schemas/Schema'
        - type: object
          properties:
            code:
              example: "error-data-not-found"
            message:
              example: "data not found"

    InvalidPubKey:
      allOf:
        - $ref: '#/components/schemas/Schema'
        - type: object
          properties:
            code:
              example: "error-user-invalid-pubkey"
            message:
              example: "invalid public key"

    InvalidPaymail:
      allOf:
        - $ref: '#/components/schemas/Schema'
        - type: object
          properties:
            code:
              example: "error-user-invalid-paymail"
            message:
              example: "invalid paymail"

    PaymailInconsistent:
      allOf:
        - $ref: '#/components/schemas/Schema'
        - type: object
          properties:
            code:
              example: "error-user-inconsistent-paymail"
            message:
              example: "inconsistent paymail address and alias/domain"

    InvalidDomain:
      allOf:
        - $ref: '#/components/schemas/Schema'
        - type: object
          properties:
            code:
              example: "error-invalid-domain"
            message:
              example: "invalid domain"

    CreatingUser:
      allOf:
        - $ref: '#/components/schemas/Schema'
        - type: object
          properties:
            code:
              example: "error-user-creating"
            message:
              example: "error creating user"

    GettingUser:
      allOf:
        - $ref: '#/components/schemas/Schema'
        - type: object
          properties:
            code:
              example: "error-unknown"
            message:
              example: "Internal server error"

    ErrTxValidation:
      allOf:
        - $ref: '#/components/schemas/Schema'
        - type: object
          properties:
            code:
              example: "error-transaction-validation"
            message:
              example: "transaction validation failed"

    ErrGettingOutputs:
      allOf:
        - $ref: '#/components/schemas/Schema'
        - type: object
          properties:
            code:
              example: "error-getting-outputs"
            message:
              example: "failed to get outputs"

    ErrUTXOSpent:
      allOf:
        - $ref: '#/components/schemas/Schema'
        - type: object
          properties:
            code:
              example: "error-utxo-spent"
            message:
              example: "UTXO is already spent"

    ErrAnnotationIndexOutOfRange:
      allOf:
        - $ref: '#/components/schemas/Schema'
        - type: object
          properties:
            code:
              example: "error-annotation-index-out-of-range"
            message:
              example: "annotation index out of range"

    ErrAnnotationIndexConversion:
      allOf:
        - $ref: '#/components/schemas/Schema'
        - type: object
          properties:
            code:
              example: "error-annotation-index-conversion"
            message:
              example: "failed to convert annotation index"

    ErrNoOperations:
      allOf:
        - $ref: '#/components/schemas/Schema'
        - type: object
          properties:
            code:
              example: "error-no-operations"
            message:
              example: "no operations to save"

    ErrTxBroadcast:
      allOf:
        - $ref: '#/components/schemas/Schema'
        - type: object
          properties:
            code:
              example: "error-tx-broadcast"
            message:
              example: "failed to broadcast transaction"
