openapi: 3.0.0
info:
  title: ignored
  version: ignored

components:
  schemas:
    Schema:
      type: object
      properties:
        code:
          type: string
          description: Error code
        message:
          type: string
          description: Error message
      required:
        - code
        - message
      additionalProperties: false

    Unauthorized:
      oneOf:
        - $ref: '#/components/schemas/Authorization'
        - $ref: '#/components/schemas/WrongAuthScopeFormat'
        - $ref: '#/components/schemas/AdminAuthOnNonAdminEndpoint'
        - $ref: '#/components/schemas/UserAuthOnNonUserEndpoint'

    Authorization:
      allOf:
        - $ref: '#/components/schemas/Schema'
        - type: object
          properties:
            code:
              example: "error-unauthorized"
            message:
              example: "unauthorized"

    WrongAuthScopeFormat:
      allOf:
        - $ref: '#/components/schemas/Schema'
        - type: object
          properties:
            code:
              example: "error-wrong-auth-scope-format"
            message:
              example: "wrong auth scope format"

    AdminAuthOnNonAdminEndpoint:
      allOf:
        - $ref: '#/components/schemas/Schema'
        - type: object
          properties:
            code:
              example: "error-admin-auth-on-non-admin-endpoint"
            message:
              example: "cannot call non-admin endpoints with admin authorization"

    UserAuthOnNonUserEndpoint:
      allOf:
        - $ref: '#/components/schemas/Schema'
        - type: object
          properties:
            code:
              example: "error-user-auth-on-non-user-endpoint"
            message:
              example: "cannot call non-user endpoints with user authorization"

    CannotBindRequest:
      allOf:
        - $ref: '#/components/schemas/Schema'
        - type: object
          properties:
            code:
              example: "error-bind-body-invalid"
            message:
              example: "cannot bind request body"

    InvalidPubKey:
      allOf:
        - $ref: '#/components/schemas/Schema'
        - type: object
          properties:
            code:
              example: "error-user-invalid-pubkey"
            message:
              example: "invalid public key"

    InvalidPaymail:
      allOf:
        - $ref: '#/components/schemas/Schema'
        - type: object
          properties:
            code:
              example: "error-user-invalid-paymail"
            message:
              example: "invalid paymail"

    PaymailInconsistent:
      allOf:
        - $ref: '#/components/schemas/Schema'
        - type: object
          properties:
            code:
              example: "error-user-inconsistent-paymail"
            message:
              example: "inconsistent paymail address and alias/domain"

    InvalidDomain:
      allOf:
        - $ref: '#/components/schemas/Schema'
        - type: object
          properties:
            code:
              example: "error-user-invalid-domain"
            message:
              example: "invalid domain"

    CreatingUser:
      allOf:
        - $ref: '#/components/schemas/Schema'
        - type: object
          properties:
            code:
              example: "error-user-creating"
            message:
              example: "error creating user"

    GettingUser:
      allOf:
        - $ref: '#/components/schemas/Schema'
        - type: object
          properties:
            code:
              example: "error-unknown"
            message:
              example: "Internal server error"
