openapi: 3.0.0
info:
  title: ignored
  version: ignored

components:
  schemas:
    ErrorSchema:
      type: object
      properties:
        code:
          type: string
          description: Error code
        message:
          type: string
          description: Error message
      required:
        - code
        - message
      additionalProperties: false

    ErrUnauthorized:
      oneOf:
        - $ref: '#/components/schemas/ErrAuthorization'
        - $ref: '#/components/schemas/ErrWrongAuthScopeFormat'
        - $ref: '#/components/schemas/ErrAdminAuthOnNonAdminEndpoint'
        - $ref: '#/components/schemas/ErrUserAuthOnNonUserEndpoint'

    ErrAuthorization:
      allOf:
        - $ref: '#/components/schemas/ErrorSchema'
        - type: object
          properties:
            code:
              example: "error-unauthorized"
            message:
              example: "unauthorized"

    ErrWrongAuthScopeFormat:
      allOf:
        - $ref: '#/components/schemas/ErrorSchema'
        - type: object
          properties:
            code:
              example: "error-wrong-auth-scope-format"
            message:
              example: "wrong auth scope format"

    ErrAdminAuthOnNonAdminEndpoint:
      allOf:
        - $ref: '#/components/schemas/ErrorSchema'
        - type: object
          properties:
            code:
              example: "error-admin-auth-on-non-admin-endpoint"
            message:
              example: "cannot call non-admin endpoints with admin authorization"

    ErrUserAuthOnNonUserEndpoint:
      allOf:
        - $ref: '#/components/schemas/ErrorSchema'
        - type: object
          properties:
            code:
              example: "error-user-auth-on-non-user-endpoint"
            message:
              example: "cannot call non-user endpoints with user authorization"

    ErrCannotBindRequest:
      allOf:
        - $ref: '#/components/schemas/ErrorSchema'
        - type: object
          properties:
            code:
              example: "error-bind-body-invalid"
            message:
              example: "cannot bind request body"

    ErrInvalidPubKey:
      allOf:
        - $ref: '#/components/schemas/ErrorSchema'
        - type: object
          properties:
            code:
              example: "error-user-invalid-pubkey"
            message:
              example: "invalid public key"

    ErrInvalidPaymail:
      allOf:
        - $ref: '#/components/schemas/ErrorSchema'
        - type: object
          properties:
            code:
              example: "error-user-invalid-paymail"
            message:
              example: "invalid paymail"

    ErrPaymailInconsistent:
      allOf:
        - $ref: '#/components/schemas/ErrorSchema'
        - type: object
          properties:
            code:
              example: "error-user-inconsistent-paymail"
            message:
              example: "inconsistent paymail address and alias/domain"

    ErrInvalidDomain:
      allOf:
        - $ref: '#/components/schemas/ErrorSchema'
        - type: object
          properties:
            code:
              example: "error-user-invalid-domain"
            message:
              example: "invalid domain"

    ErrCreatingUser:
      allOf:
        - $ref: '#/components/schemas/ErrorSchema'
        - type: object
          properties:
            code:
              example: "error-user-creating"
            message:
              example: "error creating user"

    ErrGettingUser:
      allOf:
        - $ref: '#/components/schemas/ErrorSchema'
        - type: object
          properties:
            code:
              example: "error-unknown"
            message:
              example: "Internal server error"
