openapi: 3.0.0
info:
  title: ignored
  version: ignored

components:
  schemas:
    Schema:
      type: object
      properties:
        code:
          type: string
          description: Error code
        message:
          type: string
          description: Error message
      required:
        - code
        - message
      additionalProperties: false

    AnyAuthorization:
      oneOf:
        - $ref: "#/components/schemas/Unauthorized"
        - $ref: "#/components/schemas/AuthXPubRequired"

    AdminAuthorization:
      oneOf:
        - $ref: "#/components/schemas/UserAuthOnNonUserEndpoint"
        - $ref: "#/components/schemas/AuthXPubRequired"

    UserAuthorization:
      oneOf:
        - $ref: "#/components/schemas/Unauthorized"
        - $ref: "#/components/schemas/AdminAuthOnNonAdminEndpoint"
        - $ref: "#/components/schemas/AuthXPubRequired"

    InvalidAvatarURL:
      allOf:
        - $ref: "#/components/schemas/Schema"
        - type: object
          properties:
            code:
              example: "error-user-invalid-avatar-url"
            message:
              example: "invalid avatar url"

    Unauthorized:
      allOf:
        - $ref: "#/components/schemas/Schema"
        - type: object
          properties:
            code:
              example: "error-unauthorized"
            message:
              example: "unauthorized"

    AdminAuthOnNonAdminEndpoint:
      allOf:
        - $ref: "#/components/schemas/Schema"
        - type: object
          properties:
            code:
              example: "error-admin-auth-on-non-admin-endpoint"
            message:
              example: "cannot call non-admin endpoints with admin authorization"

    UserAuthOnNonUserEndpoint:
      allOf:
        - $ref: "#/components/schemas/Schema"
        - type: object
          properties:
            code:
              example: "error-user-auth-on-non-user-endpoint"
            message:
              example: "cannot call non-user endpoints with user authorization"

    AuthXPubRequired:
      allOf:
        - $ref: "#/components/schemas/Schema"
        - type: object
          properties:
            code:
              example: "error-xpub-authorization-required"
            message:
              example: "xpub authorization required"

    CannotParseQueryParams:
      allOf:
        - $ref: "#/components/schemas/Schema"
        - type: object
          properties:
            code:
              example: "error-query-params-invalid"
            message:
              example: "cannot parse request query params"

    CannotBindRequest:
      allOf:
        - $ref: "#/components/schemas/Schema"
        - type: object
          properties:
            code:
              example: "error-bind-body-invalid"
            message:
              example: "cannot bind request body"

    Internal:
      allOf:
        - $ref: "#/components/schemas/Schema"
        - type: object
          properties:
            code:
              example: "error-internal-server-error"
            message:
              example: "internal server error"

    InvalidDataID:
      allOf:
        - $ref: "#/components/schemas/Schema"
        - type: object
          properties:
            code:
              example: "error-invalid-data-id"
            message:
              example: "invalid data id"

    DataNotFound:
      allOf:
        - $ref: "#/components/schemas/Schema"
        - type: object
          properties:
            code:
              example: "error-data-not-found"
            message:
              example: "data not found"

    InvalidPubKey:
      allOf:
        - $ref: "#/components/schemas/Schema"
        - type: object
          properties:
            code:
              example: "error-user-invalid-pubkey"
            message:
              example: "invalid public key"

    InvalidPaymail:
      allOf:
        - $ref: "#/components/schemas/Schema"
        - type: object
          properties:
            code:
              example: "error-user-invalid-paymail"
            message:
              example: "invalid paymail"

    PaymailInconsistent:
      allOf:
        - $ref: "#/components/schemas/Schema"
        - type: object
          properties:
            code:
              example: "error-user-inconsistent-paymail"
            message:
              example: "inconsistent paymail address and alias/domain"

    InvalidDomain:
      allOf:
        - $ref: "#/components/schemas/Schema"
        - type: object
          properties:
            code:
              example: "error-invalid-domain"
            message:
              example: "invalid domain"

    CreatingUser:
      allOf:
        - $ref: "#/components/schemas/Schema"
        - type: object
          properties:
            code:
              example: "error-user-creating"
            message:
              example: "error creating user"

    GettingUser:
      allOf:
        - $ref: "#/components/schemas/Schema"
        - type: object
          properties:
            code:
              example: "error-unknown"
            message:
              example: "Internal server error"

    TxSpecNoDefaultPaymailAddress:
      allOf:
        - $ref: "#/components/schemas/Schema"
        - type: object
          properties:
            code:
              example: "error-tx-spec-no-default-paymail-address"
            message:
              example: "no default paymail address"

    TxSpecOutputsRequired:
      allOf:
        - $ref: "#/components/schemas/Schema"
        - type: object
          properties:
            code:
              example: "tx-spec-output-required"
            message:
              example: "transaction outline requires at least one output"

    TxSpecOpReturnDataRequired:
      allOf:
        - $ref: "#/components/schemas/Schema"
        - type: object
          properties:
            code:
              example: "tx-spec-op-return-data-required"
            message:
              example: "data is required for OP_RETURN output"

    TxSpecFailedToDecodeHex:
      allOf:
        - $ref: "#/components/schemas/Schema"
        - type: object
          properties:
            code:
              example: "failed-to-decode-hex"
            message:
              example: "failed to decode hex"

    TxSpecInvalidPaymailReceiver:
      allOf:
        - $ref: "#/components/schemas/Schema"
        - type: object
          properties:
            code:
              example: "error-paymail-address-invalid-receiver"
            message:
              example: "receiver paymail address is invalid"

    TxSpecInvalidPaymailSender:
      allOf:
        - $ref: "#/components/schemas/Schema"
        - type: object
          properties:
            code:
              example: "error-paymail-address-invalid-sender"
            message:
              example: "sender paymail address is invalid"

    TxOutlineUserHasNotEnoughFunds:
      allOf:
        - $ref: "#/components/schemas/Schema"
        - type: object
          properties:
            code:
              example: "tx-outline-not-enough-funds"
            message:
              example: "not enough funds to make the transaction"

    TxValidation:
      allOf:
        - $ref: "#/components/schemas/Schema"
        - type: object
          properties:
            code:
              example: "error-transaction-validation"
            message:
              example: "transaction validation failed"

    GettingOutputs:
      allOf:
        - $ref: "#/components/schemas/Schema"
        - type: object
          properties:
            code:
              example: "error-getting-outputs"
            message:
              example: "failed to get outputs"

    UTXOSpent:
      allOf:
        - $ref: "#/components/schemas/Schema"
        - type: object
          properties:
            code:
              enum:
                - "error-utxo-spent"
              example: "error-utxo-spent"
            message:
              enum:
                - "UTXO is already spent"
              example: "UTXO is already spent"

    AnnotationIndexOutOfRange:
      allOf:
        - $ref: "#/components/schemas/Schema"
        - type: object
          properties:
            code:
              example: "error-annotation-index-out-of-range"
            message:
              example: "annotation index out of range"

    AnnotationIndexConversion:
      allOf:
        - $ref: "#/components/schemas/Schema"
        - type: object
          properties:
            code:
              example: "error-annotation-index-conversion"
            message:
              example: "failed to convert annotation index"

    NoOperations:
      allOf:
        - $ref: "#/components/schemas/Schema"
        - type: object
          properties:
            code:
              example: "error-no-operations"
            message:
              example: "no operations to save"

    TxBroadcast:
      allOf:
        - $ref: "#/components/schemas/Schema"
        - type: object
          properties:
            code:
              example: "error-tx-broadcast"
            message:
              example: "failed to broadcast transaction"

    FailedToGetPaginatedResults:
      allOf:
        - $ref: '#/components/schemas/Schema'
        - type: object
          properties:
            code:
              example: "error-contact-failed-to-get-paginated-results"
            message:
              example: "failed to get paginated results"

    CouldNotFindPaymail:
      allOf:
        - $ref: '#/components/schemas/Schema'
        - type: object
          properties:
            code:
              example: "error-paymail-not-found"
            message:
              example: "paymail not found"

    UserDoNotOwnPaymail:
      allOf:
        - $ref: '#/components/schemas/Schema'
        - type: object
          properties:
            code:
              example: "error-paymail-user-do-not-own"
            message:
              example: "user do not own paymail"

    ContactInvalidPaymail:
      allOf:
        - $ref: '#/components/schemas/Schema'
        - type: object
          properties:
            code:
              example: "error-contacts-invalid-paymail"
            message:
              example: "invalid paymail"

    GetContact:
      allOf:
        - $ref: '#/components/schemas/Schema'
        - type: object
          properties:
            code:
              example: "error-contact-getting-contact-failed"
            message:
              example: "getting contact failed"

    GettingPKIFailed:
      allOf:
        - $ref: '#/components/schemas/Schema'
        - type: object
          properties:
            code:
              example: "error-contact-getting-pki-failed"
            message:
              example: "getting pki for contact failed"

    ContactFailedToUpdate:
      allOf:
        - $ref: '#/components/schemas/Schema'
        - type: object
          properties:
            code:
              example: "error-contact-updating-contact-failed"
            message:
              example: "updating contact failed"

    SaveContact:
      allOf:
        - $ref: '#/components/schemas/Schema'
        - type: object
          properties:
            code:
              example: "error-contact-adding-contact-failed"
            message:
              example: "adding contact failed"

    ContactFullNameRequired:
      allOf:
        - $ref: '#/components/schemas/Schema'
        - type: object
          properties:
            code:
              example: "error-contact-full-name-required"
            message:
              example: "full name is required"

    ContactNotFound:
      allOf:
        - $ref: '#/components/schemas/Schema'
        - type: object
          properties:
            code:
              example: "error-contact-not-found"
            message:
              example: "contact not found"

    DeleteContact:
      allOf:
        - $ref: '#/components/schemas/Schema'
        - type: object
          properties:
            code:
              example: "error-contact-deleting-contact-failed"
            message:
              example: "deleting contact failed"

    ContactInWrongStatus:
      allOf:
        - $ref: '#/components/schemas/Schema'
        - type: object
          properties:
            code:
              example: "error-contact-wrong-status"
            message:
              example: "contact is in wrong status"

    MissingContactFullName:
      allOf:
        - $ref: '#/components/schemas/Schema'
        - type: object
          properties:
            code:
              example: "error-contact-full-name-missing"
            message:
              example: "missing full name in contact"

    MissingContactPaymailParam:
      allOf:
        - $ref: '#/components/schemas/Schema'
        - type: object
          properties:
            code:
              example: "error-contact-paymail-missing"
            message:
              example: "missing paymail parameter in request"

    MissingContactCreatorPaymailParam:
      allOf:
        - $ref: '#/components/schemas/Schema'
        - type: object
          properties:
            code:
              example: "error-contact-creator-paymail-missing"
            message:
              example: "missing creator paymail parameter in request"

    ContactAlreadyExists:
      allOf:
        - $ref: '#/components/schemas/Schema'
        - type: object
          properties:
            code:
              example: "error-contact-already-exists"
            message:
              example: "contact already exists"

    RequesterContactInvalid:
      allOf:
        - $ref: '#/components/schemas/Schema'
        - type: object
          properties:
            code:
              example: "error-contact-requested-contact-invalid"
            message:
              example: "requested contact paymail is invalid"

    GetPKIFailed:
      allOf:
        - $ref: '#/components/schemas/Schema'
        - type: object
          properties:
            code:
              example: "error-contact-getting-pki-failed"
            message:
              example: "getting pki for contact failed"

    UpdateContactStatus:
      allOf:
        - $ref: '#/components/schemas/Schema'
        - type: object
          properties:
            code:
              example: "error-contact-updating-status-failed"
            message:
              example: "updating contact status failed"

    BHSUnreachable:
      allOf:
        - $ref: '#/components/schemas/Schema'
        - type: object
          properties:
            code:
              example: "error-bhs-unreachable"
            message:
              example: "Block Headers Service cannot be requested"

    BHSNoSuccessResponse:
      allOf:
        - $ref: '#/components/schemas/Schema'
        - type: object
          properties:
            code:
              example: "error-bhs-no-success-response"
            message:
              example: "Block Headers Service request did not return a success response"

    BHSUnauthorized:
      allOf:
        - $ref: '#/components/schemas/Schema'
        - type: object
          properties:
            code:
              example: "error-bhs-unauthorized"
            message:
              example: "Block Headers Service returned unauthorized"

    BHSBadRequest:
      allOf:
        - $ref: '#/components/schemas/Schema'
        - type: object
          properties:
            code:
              example: "error-bhs-bad-request"
            message:
              example: "Block Headers Service bad request"

    BHSUnhealthy:
      allOf:
        - $ref: '#/components/schemas/Schema'
        - type: object
          properties:
            code:
              example: "error-bhs-unhealthy"
            message:
              example: "Block Headers Service is unhealthy"

    BHSBadURL:
      allOf:
        - $ref: '#/components/schemas/Schema'
        - type: object
          properties:
            code:
              example: "error-bhs-bad-url"
            message:
              example: "cannot create Block Headers Service url. Please check your configuration"

    BHSParsingResponse:
      allOf:
        - $ref: '#/components/schemas/Schema'
        - type: object
          properties:
            code:
              example: "error-bhs-parse-response"
            message:
              example: "cannot parse Block Headers Service response"

    InvalidBatchSize:
      allOf:
        - $ref: '#/components/schemas/Schema'
        - type: object
          properties:
            code:
              example: "error-invalid-batch-size"
            message:
              example: "batchSize must be 0 or a positive integer"

    MerkleRootNotFound:
      allOf:
        - $ref: '#/components/schemas/Schema'
        - type: object
          properties:
            code:
              example: "error-merkleroot-not-found"
            message:
              example: "No block with provided merkleroot was found"

    MerkleRootNotInLongestChain:
      allOf:
        - $ref: '#/components/schemas/Schema'
        - type: object
          properties:
            code:
              example: "error-merkleroot-not-part-of-longest-chain"
            message:
              example: "Provided merkleroot is not part of the longest chain"
