openapi: 3.0.0
info:
  title: ignored
  version: ignored

components:
  schemas:
    Data:
      type: object
      properties:
        id:
          type: string
          description: User ID
        blob:
          type: string
          description: Data blob
      required:
        - id
        - blob

    UserInfo:
      type: object
      properties:
        currentBalance:
          type: string
          format: uint64
          description: Current balance of user
      required:
        - id
        - name
