openapi: 3.0.0
info:
  title: ignored
  version: ignored

components:
  schemas:
    SharedConfig:
      description: Shared config
      type: object
      required:
        - paymailDomains
        - experimentalFeatures
      properties:
        paymailDomains:
          type: array
          items:
            type: string
          example: ["example.com"]
        experimentalFeatures:
          type: object
          additionalProperties:
            type: boolean
          example:
            pikeEnabled: true

    User:
      type: object
      properties:
        id:
          type: string
          example: "1"
        publicKey:
          type: string
          example: "76a914e069bd2e2fe3ea702c40d5e65b491b734c01686788ac"
        paymails:
          type: array
          items:
            $ref: "#/components/schemas/Paymail"
        createdAt:
          type: string
          format: date-time
          example: "2020-01-23T04:05:06Z"
        updatedAt:
          type: string
          format: date-time
          example: "2020-01-23T04:05:06Z"
      required:
        - id
        - publicKey
        - paymails
        - createdAt
        - updatedAt

    Paymail:
      type: object
      properties:
        id:
          type: integer
          x-go-type: uint
          example: 1234
        alias:
          type: string
          example: "test"
        domain:
          type: string
          example: "spv-wallet.com"
        paymail:
          type: string
          example: "test@spv-wallet.com"
        publicName:
          type: string
          example: "Test"
        avatar:
          type: string
          example: "https://spv-wallet.com/avatar.png"
      required:
        - id
        - alias
        - domain
        - paymail
        - publicName
        - avatar

    SearchPage:
      type: object
      required:
        - number
        - size
        - totalElements
        - totalPages
      properties:
        number:
          type: integer
          description: Page number for pagination
          example: 1
        size:
          type: integer
          description: Number of items per page
          example: 50
        totalElements:
          type: integer
          description: Total number of items
          example: 456
        totalPages:
          type: integer
          description: Total number of pages
          example: 10

    ExclusiveStartKeySearchPage:
      type: object
      required:
        - totalElements
        - size
        - lastEvaluatedKey
      properties:
        totalElements:
          type: integer
          description: Total number of items
          example: 456
        size:
          type: integer
          description: Number of items in returned data
          example: 50
        lastEvaluatedKey:
          type: string
          description: Last evaluated key
          example: "ac973196d58e42da6ad030dc39f5fcc343bd040e1db29b30c146e9aea9354bab"

    GetMerkleRootResult:
      type: object
      required:
        - content
        - page
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/MerkleRoot'
        page:
          $ref: '#/components/schemas/ExclusiveStartKeySearchPage'

    Data:
      type: object
      properties:
        id:
          type: string
          description: User ID
        blob:
          type: string
          description: Data blob
      required:
        - id
        - blob

    UserInfo:
      type: object
      properties:
        currentBalance:
          type: number
          x-go-type: uint64
          description: Current balance of user
      required:
        - currentBalance

    OperationsSearchResult:
      type: object
      required:
        - content
        - page
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/Operation'
        page:
          $ref: '#/components/schemas/SearchPage'

    Operation:
      type: object
      required:
        - value
        - txID
        - type
        - counterparty
        - txStatus
        - createdAt
      properties:
        value:
          type: integer
          format: int64
          description: Value of operation
          example: 1234
        txID:
          type: string
          description: Transaction ID
          example: "bb8593f85ef8056a77026ad415f02128f3768906de53e9e8bf8749fe2d66cf50"
        type:
          type: string
          description: Type of operation
          enum:
            - incoming
            - outgoing
          example: "incoming"
        counterparty:
          type: string
          description: Counterparty of operation
          example: "alice@example.com"
        txStatus:
          type: string
          description: Status of transaction
          enum:
            - CREATED
            - BROADCASTED
            - MINED
            - REVERTED
            - PROBLEMATIC
          example: "BROADCASTED"
        createdAt:
          type: string
          format: date-time
          description: Creation date of operation
          example: "2020-01-23T04:05:06Z"
        blockHeight:
          type: integer
          description: Block height of underlying transaction
          example: 1234
          x-go-type: int64
        blockHash:
          type: string
          description: Block hash of underlying transaction
          example: "000000000000000000d3577fe46b2329cce684cbcad2e8ae2129bd8874764258"

    Operations:
      type: array
      items:
        $ref: "#/components/schemas/Operation"

    AnnotatedTransactionOutline:
      allOf:
        - $ref: '#/components/schemas/TransactionHex'
        - type: object
          properties:
            annotations:
              $ref: '#/components/schemas/OutlineAnnotations'

    TransactionHex:
      type: object
      properties:
        hex:
          type: string
          description: Transaction hex
          example: "0100beef01fe9e7e0d0008020100a141b8f978b56bf196419e919b3618ac4add5914df17d777d5728c015c44032500027d1a1bab8063f41989381290074b9d5479ef1262f607962f4c8ed18f84e453be010100460ab7b19ec220bb3de54214ce6a9c0105ed44b37d1ad96f577946c6a6f3485801010012e7fb521e97454ede308ed8999016d2d696d807c999f88538d763bbbfa558da01010031af9a4d321dd4791f7b63b13a4953acbbb9fade017b8266d20140f317a43e770101007caf53cfef98f927d53639f308e46f2f2cf29049a41f5004a159d4b83eeddccf010100784dd8ea43f9565b01c6258ed8761d719675533c3c4e7d7d149b3223eb279daf0101003b6c05d7861cc67f31da3916ad8d7e52a85c25e024083f3fa3037ee5ec4fb1c801010057b6c381218bf7f2208a0c41a65daa583d4b725ed1b8023affb69d07e287d2490101000000010000000000000000000000000000000000000000000000000000000000000000ffffffff1a039e7e0d2f7461616c2e636f6d2f6ef8040de1bd70c6856e2000ffffffff01f283a012000000001976a914522cf9e7626d9bd8729e5a1398ece40dad1b6a2f88ac000000000100"
        format:
          type: string
          description: Transaction format
          enum:
            - "BEEF"
            - "RAW"
          example: "BEEF"
      required:
        - hex
        - format

    OutlineAnnotations:
      allOf:
        - $ref: "#/components/schemas/InputsAnnotations"
        - $ref: "#/components/schemas/OutputsAnnotations"

    OutputsAnnotations:
      type: object
      required:
        - outputs
      properties:
        outputs:
          type: object
          description: Map of output annotations
          additionalProperties:
            $ref: "#/components/schemas/OutputAnnotation"
          example: {
            "0": {
              "bucket": "bsv",
              "paymail": {
                "receiver": "bob@example.com",
                "reference": "1234",
                "sender": "alice@example.com",
              }
            }
          }

    InputsAnnotations:
      type: object
      required:
        - inputs
      properties:
        inputs:
          type: object
          description: Map of input annotations
          additionalProperties:
            $ref: "#/components/schemas/InputAnnotation"
          example: {
            "0": {
              "customInstructions": [
                {
                  "type": "sign",
                  "instruction": "P2PKH"
                }
              ]
            }
          }

    OutputAnnotation:
      allOf:
        - $ref: "#/components/schemas/BucketAnnotation"
        - $ref: "#/components/schemas/DataAnnotation"
        - $ref: "#/components/schemas/PaymailAnnotation"
        - $ref: "#/components/schemas/ChangeAnnotation"

    BucketAnnotation:
      type: object
      properties:
        bucket:
          type: string
          description: Type of bucket where this output should be stored.
          example: "bsv"
      required:
        - bucket

    DataAnnotation:
      type: object
      properties:
        bucket:
          type: string
          enum: ["data"]
          default: "data"
          example: "data"
      required:
        - bucket

    PaymailAnnotation:
      allOf:
        - type: object
          properties:
            bucket:
              type: string
              enum: ["bsv"]
              default: "bsv"
              example: "bsv"
            paymail:
              $ref: "#/components/schemas/PaymailAnnotationDetails"

    ChangeAnnotation:
      type: object
      properties:
        customInstructions:
          $ref: "#/components/schemas/SPVWalletCustomInstructions"

    PaymailAnnotationDetails:
      type: object
      properties:
        receiver:
          type: string
          description: Paymail address of the receiver
          example: "bob@example.com"
        reference:
          type: string
          description: Reference number used for paymail transaction
        sender:
          type: string
          description: Paymail address of the sender
          example: "alice@example.com"
      required:
        - receiver
        - reference
        - sender

    InputAnnotation:
      type: object
      properties:
        customInstructions:
          $ref: "#/components/schemas/CustomInstructions"
      required:
        - customInstructions

    CustomInstructions:
      oneOf:
        - $ref: "#/components/schemas/SPVWalletCustomInstructions"
        - $ref: "#/components/schemas/UserDefinedCustomInstructions"

    UserDefinedCustomInstructions:
      type: string
      description: Instructions about how to unlock this input.
      example: "Your custom script to unlock"

    SPVWalletCustomInstructions:
      type: array
      items:
        $ref: "#/components/schemas/SPVWalletCustomInstruction"

    SPVWalletCustomInstruction:
      properties:
        type:
          type: string
          description: Type of custom instructions
          example: "sign"
        instruction:
          type: string
          description: Custom instruction
          example: "P2PKH"
      required:
        - type
        - instruction

    RecordedOutline:
      type: object
      properties:
        txID:
          type: string
          description: ID of the transaction
      required:
        - txID

    UpsertContact:
      allOf:
        - $ref: "#/components/schemas/Contact"
        - $ref: "#/components/schemas/AdditionalInfo"

    ContactsSearchResult:
      type: object
      required:
        - content
        - page
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/Contact'
        page:
          $ref: '#/components/schemas/SearchPage'

    Contact:
      allOf:
        - $ref: '#/components/schemas/Model'
        - type: object
          properties:
            id:
              type: integer
              example: 1
              format: uint
            fullName:
              type: string
              example: "Test User"
            paymail:
              type: string
              example: "alice@spv-wallet.com"
            pubKey:
              type: string
              example: "xpub661MyMwAqRbcGpZVrSHU..."
            status:
              $ref: '#/components/schemas/ContactStatus'
          required:
            - id
            - fullName
            - pubKey
            - status
            - paymail

    ContactStatus:
      type: string
      enum:
        - unconfirmed
        - awaiting
        - confirmed
        - rejected
      example: confirmed

    AdditionalInfo:
      type: object
      additionalProperties:
        type: string

    Model:
      type: object
      properties:
        createdAt:
          type: string
          format: date-time
          example: "2025-01-01T00:00:00Z"
        updatedAt:
          type: string
          format: date-time
          example: "2025-01-01T00:00:00Z"
        deletedAt:
          type: string
          format: date-time
          example: "2025-01-01T00:00:00Z"
      required:
        - createdAt
        - updatedAt

    MerkleRoot:
      type: object
      required:
        - merkleRoot
        - blockHeight
      properties:
        merkleRoot:
          type: string
          description: Transaction ID
          example: "bb8593f85ef8056a77026ad415f02128f3768906de53e9e8bf8749fe2d66cf50"
        blockHeight:
          type: integer
          description: Block height
          example: 1234
