openapi: 3.0.0
info:
  title: ignored
  version: ignored

components:
  schemas:

    User:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: uint64
          nullable: false
          description: User ID
          example: 1
        name:
          type: string
          nullable: false
          description: User name
          example: Geralt of Rivia
      additionalProperties: false
