openapi: 3.0.0
info:
  title: SPV Wallet API requests
  version: 1.0.0

components:
  schemas:
    AdminRequest:
      type: object
      required:
        - id
      properties:
        id:
          type: integer
          format: uint64
          nullable: false
          description: Example of admin request body
          example: 1
      additionalProperties: false


    GetPaymails:
      type: object
      properties:
        domain:
          type: string
          nullable: false
          description: Paymail domain
          example: moneybutton.com
