openapi: 3.0.0
info:
  title: ignored
  version: ignored

components:
  schemas:
    CreateUser:
      type: object
      properties:
        publicKey:
          type: string
          example: "76a914e069bd2e2fe3ea702c40d5e65b491b734c01686788ac"
        paymail:
          $ref: "#/components/schemas/AddPaymail"
      required:
        - publicKey

    AddPaymail:
      type: object
      properties:
        address:
          type: string
          example: "test@spv-wallet.com"
        alias:
          type: string
          example: "test"
        domain:
          type: string
          example: "spv-wallet.com"
        publicName:
          type: string
          example: "Test"
        avatarURL:
          type: string
          example: "https://spv-wallet.com/avatar.png"
      required:
        - address
        - alias
        - domain
        - publicName
        - avatarURL

    TransactionOutline:
      allOf:
        - $ref: '../components/models.yaml#/components/schemas/TransactionHex'
        - type: object
          properties:
            annotations:
              $ref: '../components/models.yaml#/components/schemas/OutputsAnnotations'

    TransactionSpecification:
      type: object
      properties:
        outputs:
          type: array
          items:
            $ref: "#/components/schemas/TransactionOutlineOutputSpecification"
      required:
        - outputs

    TransactionOutlineOutputSpecification:
      oneOf:
        - $ref: "#/components/schemas/OpReturnOutputSpecification"
        - $ref: "#/components/schemas/PaymailOutputSpecification"
      discriminator:
        propertyName: type
        mapping:
          # Note: unfortunately we need to refer the type name after merging the schemas.
          op_return: '#/components/schemas/requests_OpReturnOutputSpecification'
          paymail: '#/components/schemas/requests_PaymailOutputSpecification'

    OpReturnOutputSpecification:
      type: object
      required:
        - type
        - data
      properties:
        type:
          type: string
          enum: [ op_return ]
          example: op_return
        dataType:
          type: string
          enum: [ hexes, strings ]
          default: strings
          example: strings
        data:
          oneOf:
            - $ref: "#/components/schemas/OpReturnHexesOutput"
            - $ref: "#/components/schemas/OpReturnStringsOutput"

    OpReturnHexesOutput:
      type: array
      items:
        type: string
        example: "68656c6c6f20776f726c64"

    OpReturnStringsOutput:
      type: array
      items:
        type: string
        example: "hello world"

    PaymailOutputSpecification:
      type: object
      properties:
        type:
          type: string
          enum: [paymail]
          example: paymail
        to:
          type: string
          example: "bob@example.com"
        satoshis:
          type: integer
          format: int64
          x-go-type: uint64
          example: 1000
        from:
          type: string
          example: "bob@example.com"
          nullable: true
      required:
        - type
        - to
        - satoshis

    UpsertContact:
      type: object
      properties:
        fullName:
          type: string
          example: "Test name"
        requesterPaymail:
          type: string
          example: "test@spv-wallet.com"
      required:
        - fullName
        - requesterPaymail
        - metadata

    UpdateContact:
      type: object
      properties:
        fullName:
          type: string
          example: "Test name"
      required:
        - fullName

    AdminCreateContact:
      type: object
      properties:
        creatorPaymail:
          type: string
          example: "example@spv-wallet.com"
        fullName:
          type: string
          example: "Test name"
      required:
        - fullName
        - creatorPaymail

    AdminConfirmContact:
      type: object
      properties:
        paymailA:
          type: string
          example: "alice@spv-wallet.com"
        paymailB:
          type: string
          example: "bob@spv-wallet.com"
      required:
        - paymailA
        - paymailB


  parameters:
    PageNumber:
      in: query
      name: page
      description: Page number for pagination
      required: false
      schema:
        type: integer
      example: 1

    PageSize:
      in: query
      name: size
      description: Number of items per page
      required: false
      schema:
        type: integer
      example: 10

    Sort:
      in: query
      name: sort
      description: Sorting order (asc or desc)
      required: false
      schema:
        type: string
      example: "asc"

    SortBy:
      name: sortBy
      in: query
      description: Field to sort by
      required: false
      schema:
        type: string
      example: "name"

    FullName:
      in: query
      name: fullName
      description: Full name of the contact
      required: false
      schema:
        type: string
      example: "Test name"

    Paymail:
      in: query
      name: paymail
      description: Paymail of the contact
      required: false
      schema:
        type: string
      example: "test@spv-wallet.com"

    ID:
      in: query
      name: id
      description: ID of the contact
      required: false
      schema:
        type: integer
      example: "1"

    PubKey:
      in: query
      name: pubKey
      description: Public key of the contact
      required: false
      schema:
        type: string
      example: "76a914e069bd2e2fe3ea702c40d5e65b491b734c01686788ac"

    Status:
      in: query
      name: status
      description: Status of the contact
      required: false
      schema:
        $ref: "../components/models.yaml#/components/schemas/ContactStatus"
      example: "confirmed"
