openapi: 3.0.0
info:
  title: ignored
  version: ignored

components:
  schemas:
    CreateUser:
      type: object
      properties:
        publicKey:
          type: string
          example: "76a914e069bd2e2fe3ea702c40d5e65b491b734c01686788ac"
        paymail:
          $ref: "#/components/schemas/AddPaymail"
      required:
        - publicKey

    AddPaymail:
      type: object
      properties:
        address:
          type: string
          example: "test@spv-wallet.com"
        alias:
          type: string
          example: "test"
        domain:
          type: string
          example: "spv-wallet.com"
        publicName:
          type: string
          example: "Test"
        avatarURL:
          type: string
          example: "https://spv-wallet.com/avatar.png"
      required:
        - address
        - alias
        - domain
        - publicName
        - avatarURL
    AnnotatedTransaction:
      type: object
      properties:
        hex:
          type: string
          description: Transaction hex
        format:
          type: string
          description: Transaction format
          example: "BEEF"
        annotations:
          $ref: '../components/models.yaml#/components/schemas/Annotations'
      required:
        - hex
        - format

    TransactionSpecification:
      type: object
      properties:
        hex:
          type: string
          description: Transaction hex
        format:
          type: string
          description: Transaction format
          example: "BEEF"
        annotations:
          $ref: '../components/models.yaml#/components/schemas/Annotations'
      required:
        - hex
        - format

  parameters:
    PageNumber:
      in: query
      name: page
      description: Page number for pagination
      required: false
      schema:
        type: integer
      example: 1

    PageSize:
      in: query
      name: size
      description: Number of items per page
      required: false
      schema:
        type: integer
      example: 10

    Sort:
      in: query
      name: sort
      description: Sorting order (asc or desc)
      required: false
      schema:
        type: string
      example: "asc"

    SortBy:
      name: sortBy
      in: query
      description: Field to sort by
      required: false
      schema:
        type: string
      example: "name"
