openapi: 3.0.0
info:
  title: ignored
  version: ignored

components:
  responses:
    NotAuthorized:
      description: Security requirements failed
      content:
        application/json:
          schema:
            $ref: "./errors.yaml#/components/schemas/ErrUnauthorized"

    AdminUserBadRequest:
      description: Bad request is an error that occurs when the request is malformed.
      content:
        application/json:
          schema:
            oneOf:
              - $ref: "./errors.yaml#/components/schemas/ErrCannotBindRequest"
              - $ref: "./errors.yaml#/components/schemas/ErrInvalidPubKey"
              - $ref: "./errors.yaml#/components/schemas/ErrInvalidPaymail"
              - $ref: "./errors.yaml#/components/schemas/ErrPaymailInconsistent"
              - $ref: "./errors.yaml#/components/schemas/ErrInvalidDomain"

    AdminCreateUserInternalServerError:
      description: Internal error while creating user
      content:
        application/json:
          schema:
            $ref: "./errors.yaml#/components/schemas/ErrCreatingUser"

    AdminCreateUserSuccess:
      description: User created
      content:
        application/json:
          schema:
            $ref: "./models.yaml#/components/schemas/User"

    AdminAddPaymailSuccess:
      description: Paymail added to user
      content:
        application/json:
          schema:
            $ref: "./models.yaml#/components/schemas/Paymail"

    AdminGetUser:
      description: User found
      content:
        application/json:
          schema:
            $ref: "./models.yaml#/components/schemas/User"

    AdminGetUserInternalServerError:
      description: Internal error while getting user
      content:
        application/json:
          schema:
            $ref: "./errors.yaml#/components/schemas/ErrGettingUser"
