openapi: 3.0.0
info:
  title: ignored
  version: ignored

components:
  schemas:
    UserExampleResponse:
      allOf:
        - $ref: '#/components/schemas/CommonResponse'
        - $ref: './models.yaml#/components/schemas/User'
        - type: object
          properties:
            additionalPropertyExample:
              type: string
              description: The user model additional property example
              example: "example"

    CommonResponse:
      type: object
      required:
        - timestamp
      description: Common response object
      properties:
        timestamp:
          type: string
          format: date-time
          nullable: false
