# Get Golang
FROM golang:1.17.8-alpine

# Version
LABEL version="1.0" name="BuxServer"

# Set the timezone (#RUN echo "UTC" > /etc/timezone)
RUN apk update && \
    apk add -U tzdata build-base && \
    cp /usr/share/zoneinfo/EST5EDT /etc/localtime && \
    echo "UTC" > /etc/timezone

# Set the working directory
WORKDIR /go/src/github.com/BuxOrg/bux-server

# Expose the port to the server
EXPOSE 3003

# Move the current code into the directory
COPY . /go/src/github.com/BuxOrg/bux-server

# Compile and build / Move the go application to the right path (/bin/) (hack)
RUN go build -i cmd/server/main.go && go build cmd/server/main.go && mv main /go/bin/

# Run the application
CMD ["main"]
