openapi: 3.0.0
info:
  title: ignored
  version: ignored
paths:
  # GET STATUS
  /api/v1/admin:
    get:
      operationId: GET admin
      tags:
        - Admin endpoints
      summary: Get the admin settings
      description: >-
        This endpoint returns the admin settings.
      requestBody:
        required: true
        description: 'Test object in body'
        content:
          application/json:
            schema:
              $ref: "../components/requests.yaml#/components/schemas/AdminRequest"
      responses:
        200:
          description: Success
        401:
          $ref: "../components/errors.yaml#/components/responses/NotAuthorized"


  /api/v1/admin/paymails:
    get:
      tags:
        - Admin endpoints
      summary: Get all paymails
      description: >-
        This endpoint returns the paymails
      requestBody:
        required: true
        description: 'Filter paymail'
        content:
          application/json:
            schema:
              $ref: "../components/requests.yaml#/components/schemas/GetPaymails"
      responses:
        200:
          description: Success
        401:
          $ref: "../components/errors.yaml#/components/responses/NotAuthorized"
