openapi: 3.0.0
info:
  title: ignored
  version: ignored
paths:
  /api/v2/status:
    get:
      tags:
        - Base endpoints
      summary: Get status
      description: >-
        This endpoint returns status. It can be obtained by everyone
      responses:
          200:
            description: Success

  /api/v2/configs/shared:
    get:
      security:
        - XPubAuth:
            - "admin"
            - "user"
      tags:
        - Base endpoints
      summary: Get shared config
      description: >-
        This endpoint returns shared config. It can be obtained by both admin and user.
      responses:
        200:
          $ref: "../components/responses.yaml#/components/responses/SharedConfig"
        401:
          $ref: "../components/errors.yaml#/components/responses/NotAuthorized"
