openapi: 3.0.0
info:
  title: ignored
  version: ignored
paths:
  /api/v2/configs/shared:
    get:
      operationId: sharedConfig
      security:
        - XPubAuth:
            - "admin"
            - "user"
      tags:
        - Admin endpoints
        - Configurations
      summary: Get shared config
      description: >-
        This endpoint returns shared config. It can be obtained by both admin and user.
      responses:
        200:
          $ref: "../components/responses.yaml#/components/responses/SharedConfig"
        401:
          $ref: "../components/responses.yaml#/components/responses/NotAuthorized"

  /api/v2/test/errors:
    get:
      tags:
        - Test errors
      parameters:
        - name: fail
          in: query
          description: Fail
          required: false
          schema:
            $ref: "../components/models.yaml#/components/schemas/FailingPoint"
      responses:
        200:
          description: Success
        default:
          $ref: "../components/responses.yaml#/components/responses/ProblemDetails"
