openapi: 3.0.0
info:
  title: ignored
  version: ignored
paths:

  # GET STATUS
  /api/v1/policy:
    get:
      operationId: GET policy
      tags:
        - Base endpoints
      summary: Get the policy settings
      description: >-
        This endpoint returns the policy settings.
      responses:
        200:
          description: Success
