openapi: 3.0.0
info:
  title: ignored
  version: ignored
paths:

  /api/v2/users/current:
    get:
      operationId: currentUser
      security:
        - XPubAuth:
            - "user"
      tags:
        - User
      summary: Get current user
      description: >-
        This endpoint return balance of current authenticated user
      responses:
        200:
          $ref: "../components/responses.yaml#/components/responses/GetCurrentUserSuccess"
        401:
          $ref: "../components/responses.yaml#/components/responses/UserNotAuthorized"
        500:
          $ref: "../components/responses.yaml#/components/responses/InternalServerError"

  /api/v2/data/{id}:
    get:
      operationId: dataById
      security:
        - XPubAuth:
            - "user"
      tags:
        - Data
      summary: Get data for user
      description: >-
        This endpoint gets data by its id for authenticated user
      parameters:
        - name: id
          in: path
          description: Data ID
          required: true
          schema:
            type: string
      responses:
        200:
          $ref: "../components/responses.yaml#/components/responses/GetDataSuccess"
        400:
          $ref: "../components/responses.yaml#/components/responses/UserBadRequest"
        401:
          $ref: "../components/responses.yaml#/components/responses/UserNotAuthorized"
        404:
          $ref: "../components/responses.yaml#/components/responses/GetDataNotFound"
        500:
          $ref: "../components/responses.yaml#/components/responses/InternalServerError"

  /api/v2/operations/search:
    get:
      operationId: searchOperations
      security:
        - XPubAuth:
            - "user"
      tags:
        - Operations
      summary: Get operations for user
      description: >-
        This endpoint allows to search operations for authenticated user
      parameters:
        - $ref: "../components/requests.yaml#/components/parameters/PageNumber"
        - $ref: "../components/requests.yaml#/components/parameters/PageSize"
        - $ref: "../components/requests.yaml#/components/parameters/Sort"
        - $ref: "../components/requests.yaml#/components/parameters/SortBy"
      responses:
        200:
          $ref: "../components/responses.yaml#/components/responses/SearchOperationsSuccess"
        400:
          $ref: "../components/responses.yaml#/components/responses/SearchBadRequest"
        401:
          $ref: "../components/responses.yaml#/components/responses/UserNotAuthorized"
        500:
          $ref: "../components/responses.yaml#/components/responses/InternalServerError"

  /api/v2/transactions:
    post:
      operationId: recordTransactionOutline
      security:
        - XPubAuth:
            - "user"
      tags:
        - Transactions
      summary: Record transaction outline
      description: >-
        This endpoint allows to record transaction outline for authenticated user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "../components/requests.yaml#/components/schemas/TransactionOutline"
      responses:
        201:
          $ref: "../components/responses.yaml#/components/responses/RecordTransactionSuccess"
        400:
          $ref: "../components/responses.yaml#/components/responses/RecordTransactionBadRequest"
        401:
          $ref: "../components/responses.yaml#/components/responses/UserNotAuthorized"
        500:
          $ref: "../components/responses.yaml#/components/responses/RecordTransactionInternalServerError"

  /api/v2/transactions/outlines:
    post:
      operationId: createTransactionOutline
      security:
        - XPubAuth:
            - "user"
      tags:
        - Transactions
      summary: Create transaction outline
      description: >-
        This endpoint allows to create transaction outline for authenticated user
      parameters:
        - name: format
          in: query
          description: Required format of transaction hex
          schema:
            type: string
            enum:
              - "beef"
              - "raw"
            default: "beef"
          example: "beef"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "../components/requests.yaml#/components/schemas/TransactionSpecification"
      responses:
        200:
          $ref: "../components/responses.yaml#/components/responses/CreateTransactionOutlineSuccess"
        400:
          $ref: "../components/responses.yaml#/components/responses/CreateTransactionOutlineBadRequest"
        422:
          $ref: "../components/responses.yaml#/components/responses/CreateTransactionOutlineUnprocessable"
        401:
          $ref: "../components/responses.yaml#/components/responses/UserNotAuthorized"
        500:
          $ref: "../components/responses.yaml#/components/responses/InternalServerError"


  /api/v2/contacts:
    get:
      operationId: getContacts
      security:
        - XPubAuth:
            - "user"
      tags:
        - Contacts
      summary: Get contacts
      description: >-
        This endpoint allows to get contacts for authenticated user
      parameters:
        - $ref: "../components/requests.yaml#/components/parameters/PageNumber"
        - $ref: "../components/requests.yaml#/components/parameters/PageSize"
        - $ref: "../components/requests.yaml#/components/parameters/Sort"
        - $ref: "../components/requests.yaml#/components/parameters/SortBy"
        - $ref: "../components/requests.yaml#/components/parameters/FullName"
        - $ref: "../components/requests.yaml#/components/parameters/Paymail"
        - $ref: "../components/requests.yaml#/components/parameters/ID"
        - $ref: "../components/requests.yaml#/components/parameters/PubKey"
        - $ref: "../components/requests.yaml#/components/parameters/Status"
      responses:
        200:
          $ref: "../components/responses.yaml#/components/responses/SearchContactsSuccess"
        401:
          $ref: "../components/responses.yaml#/components/responses/UserNotAuthorized"
        500:
          $ref: "../components/responses.yaml#/components/responses/ContactSearchInternalServerError"


  /api/v2/contacts/{paymail}:
    put:
      operationId: upsertContact
      security:
        - XPubAuth:
            - "user"
      tags:
        - Contacts
      summary: Add contact
      description: >-
        Add or update contact. When adding a new contact, the system utilizes Paymail's PIKE capability to dispatch an invitation request, asking the counterparty to include the current user in their contacts.
      parameters:
        - name: paymail
          in: path
          description: >-
            Paymail address of the contact that the user would like to add/modify
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "../components/requests.yaml#/components/schemas/UpsertContact"
      responses:
        200:
          $ref: "../components/responses.yaml#/components/responses/ContactSuccess"
        400:
          $ref: "../components/responses.yaml#/components/responses/UpsertContactBadRequest"
        401:
          $ref: "../components/responses.yaml#/components/responses/UserNotAuthorized"
        404:
            $ref: "../components/responses.yaml#/components/responses/UpsertContactNotFound"
        500:
          $ref: "../components/responses.yaml#/components/responses/ContactUpsertInternalServerError"

    get:
      operationId: getContact
      security:
        - XPubAuth:
            - "user"
      tags:
        - Contacts
      summary: Get contact
      description: >-
        This endpoint allows to get contact for authenticated user
      parameters:
        - name: paymail
          in: path
          description: >-
            Paymail address of the contact that the user would like to get
          required: true
          schema:
            type: string
      responses:
        200:
          $ref: "../components/responses.yaml#/components/responses/ContactSuccess"
        401:
          $ref: "../components/responses.yaml#/components/responses/UserNotAuthorized"
        404:
          $ref: "../components/responses.yaml#/components/responses/ContactNotFound"
        500:
          $ref: "../components/responses.yaml#/components/responses/GetContactInternalServerError"

    delete:
      operationId: removeContact
      security:
        - XPubAuth:
            - "user"
      tags:
        - Contacts
      summary: Remove contact
      description: >-
        This endpoint allows to remove contact for authenticated user
      parameters:
        - name: paymail
          in: path
          description: >-
            Paymail address of the contact that the user would like to remove
          required: true
          schema:
            type: string
      responses:
        200:
          description: Success - contact removed
        401:
          $ref: "../components/responses.yaml#/components/responses/UserNotAuthorized"
        500:
          $ref: "../components/responses.yaml#/components/responses/DeleteContactInternalServerError"

  /api/v2/contacts/{paymail}/confirmation:
    post:
      operationId: confirmContact
      security:
        - XPubAuth:
            - "user"
      tags:
        - Contacts
      summary: Confirm contact
      description: >-
        This endpoint allows to confirm contact for authenticated user
      parameters:
        - name: paymail
          in: path
          description: >-
            Paymail address of the contact that the user would like to confirm
          required: true
          schema:
            type: string
      responses:
        200:
          description: Success - contact confirmed
        400:
          $ref: "../components/responses.yaml#/components/responses/UpdateContactBadRequest"
        401:
          $ref: "../components/responses.yaml#/components/responses/UserNotAuthorized"
        404:
          $ref: "../components/responses.yaml#/components/responses/ContactNotFound"
        500:
          $ref: "../components/responses.yaml#/components/responses/InternalServerError"

    delete:
      operationId: unconfirmContact
      security:
        - XPubAuth:
            - "user"
      tags:
        - Contacts
      summary: Unconfirm contact
      description: >-
        Unconfirm contact. For contact with status "confirmed" change status to "unconfirmed"
      parameters:
        - name: paymail
          in: path
          description: >-
            Paymail address of the contact that the user would like to unconfirm
          required: true
          schema:
            type: string
      responses:
        200:
          description: Success - contact removed
        400:
          $ref: "../components/responses.yaml#/components/responses/UpdateContactBadRequest"
        401:
          $ref: "../components/responses.yaml#/components/responses/UserNotAuthorized"
        404:
          $ref: "../components/responses.yaml#/components/responses/ContactNotFound"
        500:
          $ref: "../components/responses.yaml#/components/responses/InternalServerError"

  /api/v2/contacts/invitations/{paymail}:
    delete:
      operationId: rejectInvitation
      security:
        - XPubAuth:
            - "user"
      tags:
        - Contacts
      summary: Reject invitation
      description: >-
        This endpoint allows to reject invitation for authenticated user
      parameters:
        - name: paymail
          in: path
          description: >-
            Paymail address of the contact that the user would like to reject
          required: true
          schema:
            type: string
      responses:
        200:
          description: Success - invitation removed
        400:
          $ref: "../components/responses.yaml#/components/responses/UpdateContactBadRequest"
        401:
          $ref: "../components/responses.yaml#/components/responses/UserNotAuthorized"
        404:
          $ref: "../components/responses.yaml#/components/responses/ContactNotFound"
        500:
          $ref: "../components/responses.yaml#/components/responses/InternalServerError"

  /api/v2/contacts/invitations/{paymail}/contacts:
    post:
      operationId: acceptInvitation
      security:
        - XPubAuth:
            - "user"
      tags:
        - Contacts
      summary: Accept invitation
      description: >-
        This endpoint allows to accept invitation for authenticated user
      parameters:
        - name: paymail
          in: path
          description: >-
            Paymail address of the contact that the user would like to accept
          required: true
          schema:
            type: string
      responses:
        200:
          description: Success - invitation accepted
        400:
          $ref: "../components/responses.yaml#/components/responses/UpdateContactBadRequest"
        401:
          $ref: "../components/responses.yaml#/components/responses/UserNotAuthorized"
        404:
          $ref: "../components/responses.yaml#/components/responses/ContactNotFound"
        500:
          $ref: "../components/responses.yaml#/components/responses/InternalServerError"
