openapi: 3.0.0
info:
  title: ignored
  version: ignored
paths:

  /api/v2/users/current:
    get:
      security:
        - XPubAuth:
            - "user"
      tags:
        - User endpoints
      summary: Get current user
      description: >-
        This endpoint return balance of current authenticated user
      responses:
        200:
          $ref: "../components/responses.yaml#/components/responses/GetCurrentUserSuccess"
        401:
          $ref: "../components/responses.yaml#/components/responses/UserNotAuthorized"
        500:
          $ref: "../components/responses.yaml#/components/responses/InternalServerError"

  /api/v2/data/{id}:
    get:
      security:
        - XPubAuth:
            - "user"
      tags:
        - User endpoints
      summary: Get data for user
      description: >-
        This endpoint gets data by its id for authenticated user
      parameters:
        - name: id
          in: path
          description: Data ID
          required: true
          schema:
            type: string
      responses:
        200:
          $ref: "../components/responses.yaml#/components/responses/GetDataSuccess"
        400:
          $ref: "../components/responses.yaml#/components/responses/UserBadRequest"
        401:
          $ref: "../components/responses.yaml#/components/responses/UserNotAuthorized"
        404:
          $ref: "../components/responses.yaml#/components/responses/GetDataNotFound"
        500:
          $ref: "../components/responses.yaml#/components/responses/InternalServerError"

  /api/v2/operations/search:
    get:
      security:
        - XPubAuth:
            - "user"
      tags:
        - User endpoints
      summary: Get operations for user
      description: >-
        This endpoint allows to search operations for authenticated user
      parameters:
        - $ref: "../components/requests.yaml#/components/parameters/PageNumber"
        - $ref: "../components/requests.yaml#/components/parameters/PageSize"
        - $ref: "../components/requests.yaml#/components/parameters/Sort"
        - $ref: "../components/requests.yaml#/components/parameters/SortBy"
      responses:
        200:
          $ref: "../components/responses.yaml#/components/responses/SearchOperationsSuccess"
        400:
          $ref: "../components/responses.yaml#/components/responses/SearchBadRequest"
        401:
          $ref: "../components/responses.yaml#/components/responses/UserNotAuthorized"
        500:
          $ref: "../components/responses.yaml#/components/responses/InternalServerError"
