// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/transaction/broadcast/callback": {
            "post": {
                "security": [
                    {
                        "callback-auth": []
                    }
                ],
                "tags": [
                    "Transactions"
                ],
                "summary": "Broadcast Callback",
                "parameters": [
                    {
                        "description": "Transaction",
                        "name": "transaction",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/broadcast.SubmittedTx"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/access-key": {
            "get": {
                "security": [
                    {
                        "x-auth-xpub": []
                    }
                ],
                "description": "Get access key",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Access-key"
                ],
                "summary": "Get access key",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "x-auth-xpub": []
                    }
                ],
                "description": "Create access key",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Access-key"
                ],
                "summary": "Create access key",
                "parameters": [
                    {
                        "description": "CreateAccessKey model containing metadata",
                        "name": "CreateAccessKey",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/accesskeys.CreateAccessKey"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "x-auth-xpub": []
                    }
                ],
                "description": "Revoke access key",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Access-key"
                ],
                "summary": "Revoke access key",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    }
                }
            }
        },
        "/v1/access-key/count": {
            "post": {
                "security": [
                    {
                        "x-auth-xpub": []
                    }
                ],
                "description": "Count of access keys",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Access-key"
                ],
                "summary": "Count of access keys",
                "parameters": [
                    {
                        "description": "CountRequestParameters model containing metadata and conditions",
                        "name": "CountRequestParameters",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/actions.CountRequestParameters"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/access-key/search": {
            "post": {
                "security": [
                    {
                        "x-auth-xpub": []
                    }
                ],
                "description": "Search access key",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Access-key"
                ],
                "summary": "Search access key",
                "parameters": [
                    {
                        "description": "SearchRequestParameters model containing metadata, conditions and query params",
                        "name": "SearchRequestParameters",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/actions.SearchRequestParameters"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/admin/access-keys/count": {
            "post": {
                "security": [
                    {
                        "x-auth-xpub": []
                    }
                ],
                "description": "Access Keys Count",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Access Keys Count",
                "parameters": [
                    {
                        "description": "CountRequestParameters model containing metadata and conditions",
                        "name": "CountRequestParameters",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/actions.CountRequestParameters"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/admin/access-keys/search": {
            "post": {
                "security": [
                    {
                        "x-auth-xpub": []
                    }
                ],
                "description": "Access Keys Search",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Access Keys Search",
                "parameters": [
                    {
                        "description": "SearchRequestParameters model containing metadata, conditions and query params",
                        "name": "SearchRequestParameters",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/actions.SearchRequestParameters"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/admin/destinations/count": {
            "post": {
                "security": [
                    {
                        "x-auth-xpub": []
                    }
                ],
                "description": "Count destinations",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Count destinations",
                "parameters": [
                    {
                        "description": "CountRequestParameters model containing metadata and conditions",
                        "name": "CountRequestParameters",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/actions.CountRequestParameters"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/admin/destinations/search": {
            "post": {
                "security": [
                    {
                        "x-auth-xpub": []
                    }
                ],
                "description": "Search for destinations",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Search for destinations",
                "parameters": [
                    {
                        "description": "SearchRequestParameters model containing metadata, conditions and query params",
                        "name": "SearchRequestParameters",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/actions.SearchRequestParameters"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/admin/paymail/create": {
            "post": {
                "security": [
                    {
                        "x-auth-xpub": []
                    }
                ],
                "description": "Create paymail",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Create paymail",
                "parameters": [
                    {
                        "description": "CreatePaymail model containing paymail information",
                        "name": "CreatePaymail",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin.CreatePaymail"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    }
                }
            }
        },
        "/v1/admin/paymail/delete": {
            "delete": {
                "security": [
                    {
                        "x-auth-xpub": []
                    }
                ],
                "description": "Delete paymail",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Delete paymail",
                "parameters": [
                    {
                        "description": "PaymailAddress model containing paymail address to delete",
                        "name": "PaymailAddress",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/admin/paymail/get": {
            "post": {
                "security": [
                    {
                        "x-auth-xpub": []
                    }
                ],
                "description": "Get paymail",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Get paymail",
                "parameters": [
                    {
                        "description": "PaymailAddress model containing paymail address",
                        "name": "PaymailAddress",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin.PaymailAddress"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/admin/paymails/count": {
            "post": {
                "security": [
                    {
                        "x-auth-xpub": []
                    }
                ],
                "description": "Paymail addresses count",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Paymail addresses count",
                "parameters": [
                    {
                        "description": "CountRequestParameters model containing metadata and conditions",
                        "name": "CountRequestParameters",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/actions.CountRequestParameters"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/admin/paymails/search": {
            "post": {
                "security": [
                    {
                        "x-auth-xpub": []
                    }
                ],
                "description": "Paymail addresses search",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Paymail addresses search",
                "parameters": [
                    {
                        "description": "SearchRequestParameters model containing metadata, conditions and query params",
                        "name": "SearchRequestParameters",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/actions.SearchRequestParameters"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/admin/stats": {
            "get": {
                "security": [
                    {
                        "x-auth-xpub": []
                    }
                ],
                "description": "Get stats",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Get stats",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/admin/status": {
            "get": {
                "security": [
                    {
                        "x-auth-xpub": []
                    }
                ],
                "description": "Get status",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Get status",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/admin/transactions/count": {
            "post": {
                "security": [
                    {
                        "x-auth-xpub": []
                    }
                ],
                "description": "Count transactions",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Count transactions",
                "parameters": [
                    {
                        "description": "CountRequestParameters model containing metadata and conditions",
                        "name": "CountRequestParameters",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/actions.CountRequestParameters"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/admin/transactions/record": {
            "post": {
                "security": [
                    {
                        "x-auth-xpub": []
                    }
                ],
                "description": "Record transactions",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Record transactions",
                "parameters": [
                    {
                        "description": "RecordTransaction model containing hex of the transaction to record",
                        "name": "RecordTransaction",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin.RecordTransaction"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    }
                }
            }
        },
        "/v1/admin/transactions/search": {
            "post": {
                "security": [
                    {
                        "x-auth-xpub": []
                    }
                ],
                "description": "Search for transactions",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Search for transactions",
                "parameters": [
                    {
                        "description": "SearchRequestParameters model containing metadata, conditions and query params",
                        "name": "SearchRequestParameters",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/actions.SearchRequestParameters"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/admin/utxos/count": {
            "post": {
                "security": [
                    {
                        "x-auth-xpub": []
                    }
                ],
                "description": "Count utxos",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Count utxos",
                "parameters": [
                    {
                        "description": "CountRequestParameters model containing metadata and conditions",
                        "name": "CountRequestParameters",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/actions.CountRequestParameters"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/admin/utxos/search": {
            "post": {
                "security": [
                    {
                        "x-auth-xpub": []
                    }
                ],
                "description": "Search for utxos",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Search for utxos",
                "parameters": [
                    {
                        "description": "SearchRequestParameters model containing metadata, conditions and query params",
                        "name": "SearchRequestParameters",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/actions.SearchRequestParameters"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/admin/xpub": {
            "post": {
                "security": [
                    {
                        "x-auth-xpub": []
                    }
                ],
                "description": "Create xPub",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Create xPub",
                "parameters": [
                    {
                        "description": "CreateXpub model containing key and metadata",
                        "name": "CreateXpub",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin.CreateXpub"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    }
                }
            }
        },
        "/v1/admin/xpubs/count": {
            "post": {
                "security": [
                    {
                        "x-auth-xpub": []
                    }
                ],
                "description": "Count xpubs",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Count xpubs",
                "parameters": [
                    {
                        "description": "CountRequestParameters model containing metadata and conditions",
                        "name": "CountRequestParameters",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/actions.CountRequestParameters"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/admin/xpubs/search": {
            "post": {
                "security": [
                    {
                        "x-auth-xpub": []
                    }
                ],
                "description": "Search for xpubs",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Search for xpubs",
                "parameters": [
                    {
                        "description": "SearchRequestParameters model containing metadata, conditions and query params",
                        "name": "SearchRequestParameters",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/actions.SearchRequestParameters"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/contact": {
            "post": {
                "security": [
                    {
                        "bux-auth-xpub": []
                    }
                ],
                "description": "Create contact",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Contact"
                ],
                "summary": "Create contact",
                "parameters": [
                    {
                        "type": "string",
                        "description": "fullName",
                        "name": "fullName",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "paymail",
                        "name": "paymail",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "pubKey",
                        "name": "pubKey",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "metadata",
                        "name": "metadata",
                        "in": "query"
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    }
                }
            }
        },
        "/v1/destination": {
            "get": {
                "security": [
                    {
                        "x-auth-xpub": []
                    }
                ],
                "description": "Get a destination",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Destinations"
                ],
                "summary": "Get a destination",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Destination ID",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Destination address",
                        "name": "address",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Destination locking script",
                        "name": "locking_script",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "x-auth-xpub": []
                    }
                ],
                "description": "Create a new destination",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Destinations"
                ],
                "summary": "Create a new destination",
                "parameters": [
                    {
                        "description": "CreateDestination model containing metadata",
                        "name": "CreateDestination",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/destinations.CreateDestination"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "x-auth-xpub": []
                    }
                ],
                "description": "Update destination",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Destinations"
                ],
                "summary": "Update destination",
                "parameters": [
                    {
                        "description": "UpdateDestination model containing an id, address, locking_script and metadata",
                        "name": "UpdateDestination",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/destinations.UpdateDestination"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/destination/count": {
            "post": {
                "security": [
                    {
                        "x-auth-xpub": []
                    }
                ],
                "description": "Count Destinations",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Destinations"
                ],
                "summary": "Count Destinations",
                "parameters": [
                    {
                        "description": "CountRequestParameters model containing metadata and conditions",
                        "name": "CountRequestParameters",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/actions.CountRequestParameters"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/destination/search": {
            "post": {
                "security": [
                    {
                        "x-auth-xpub": []
                    }
                ],
                "description": "Search for a destination",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Destinations"
                ],
                "summary": "Search for a destination",
                "parameters": [
                    {
                        "description": "SearchRequestParameters model containing metadata, conditions and query params",
                        "name": "SearchRequestParameters",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/actions.SearchRequestParameters"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/transaction": {
            "get": {
                "security": [
                    {
                        "x-auth-xpub": []
                    }
                ],
                "description": "Get transaction by id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transactions"
                ],
                "summary": "Get transaction by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "x-auth-xpub": []
                    }
                ],
                "description": "New transaction",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transactions"
                ],
                "summary": "New transaction",
                "parameters": [
                    {
                        "description": "NewTransaction model containing the transaction config and metadata",
                        "name": "NewTransaction",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/transactions.NewTransaction"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "x-auth-xpub": []
                    }
                ],
                "description": "Update transaction",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transactions"
                ],
                "summary": "Update transaction",
                "parameters": [
                    {
                        "description": "UpdateTransaction model containing the transaction id and metadata",
                        "name": "UpdateTransaction",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/transactions.UpdateTransaction"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/transaction/count": {
            "post": {
                "security": [
                    {
                        "x-auth-xpub": []
                    }
                ],
                "description": "Count of transactions",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transactions"
                ],
                "summary": "Count of transactions",
                "parameters": [
                    {
                        "description": "CountRequestParameters model containing metadata and conditions",
                        "name": "CountRequestParameters",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/actions.CountRequestParameters"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/transaction/record": {
            "post": {
                "security": [
                    {
                        "x-auth-xpub": []
                    }
                ],
                "description": "Record transaction",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transactions"
                ],
                "summary": "Record transaction",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/transaction/search": {
            "post": {
                "security": [
                    {
                        "x-auth-xpub": []
                    }
                ],
                "description": "Search transaction",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transactions"
                ],
                "summary": "Search transaction",
                "parameters": [
                    {
                        "description": "SearchRequestParameters model containing metadata, conditions and query params",
                        "name": "SearchRequestParameters",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/actions.SearchRequestParameters"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/utxo": {
            "get": {
                "security": [
                    {
                        "x-auth-xpub": []
                    }
                ],
                "description": "Get UTXO",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UTXO"
                ],
                "summary": "Get UTXO",
                "parameters": [
                    {
                        "type": "string",
                        "description": "tx_id",
                        "name": "tx_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "output_index",
                        "name": "output_index",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/utxo/count": {
            "post": {
                "security": [
                    {
                        "x-auth-xpub": []
                    }
                ],
                "description": "Count of UTXOs",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UTXO"
                ],
                "summary": "Count of UTXOs",
                "parameters": [
                    {
                        "description": "CountRequestParameters model containing metadata and conditions",
                        "name": "CountRequestParameters",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/actions.CountRequestParameters"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/utxo/search": {
            "post": {
                "security": [
                    {
                        "x-auth-xpub": []
                    }
                ],
                "description": "Search UTXO",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UTXO"
                ],
                "summary": "Search UTXO",
                "parameters": [
                    {
                        "description": "SearchRequestParameters model containing metadata, conditions and query params",
                        "name": "SearchRequestParameters",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/actions.SearchRequestParameters"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/xpub": {
            "get": {
                "security": [
                    {
                        "x-auth-xpub": []
                    }
                ],
                "description": "Get xPub",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "xPub"
                ],
                "summary": "Get xPub",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "x-auth-xpub": []
                    },
                    {
                        "bux-auth-xpub": []
                    }
                ],
                "description": "Update xPub",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "xPub"
                ],
                "summary": "Update xPub",
                "parameters": [
                    {
                        "description": "Metadata which should replace the already existing one",
                        "name": "Metadata",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/engine.Metadata"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        }
    },
    "definitions": {
        "accesskeys.CreateAccessKey": {
            "type": "object",
            "properties": {
                "metadata": {
                    "$ref": "#/definitions/engine.Metadata"
                }
            }
        },
        "actions.CountRequestParameters": {
            "type": "object",
            "properties": {
                "conditions": {
                    "type": "object",
                    "additionalProperties": true
                },
                "metadata": {
                    "$ref": "#/definitions/engine.Metadata"
                }
            }
        },
        "actions.SearchRequestParameters": {
            "type": "object",
            "properties": {
                "conditions": {
                    "type": "object",
                    "additionalProperties": true
                },
                "metadata": {
                    "$ref": "#/definitions/engine.Metadata"
                },
                "params": {
                    "$ref": "#/definitions/datastore.QueryParams"
                }
            }
        },
        "admin.CreatePaymail": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "avatar": {
                    "type": "string"
                },
                "metadata": {
                    "$ref": "#/definitions/engine.Metadata"
                },
                "public_name": {
                    "type": "string"
                },
                "xpub_id": {
                    "type": "string"
                }
            }
        },
        "admin.CreateXpub": {
            "type": "object",
            "properties": {
                "key": {
                    "type": "string"
                },
                "metadata": {
                    "$ref": "#/definitions/engine.Metadata"
                }
            }
        },
        "admin.PaymailAddress": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                }
            }
        },
        "admin.RecordTransaction": {
            "type": "object",
            "properties": {
                "hex": {
                    "type": "string"
                }
            }
        },
        "broadcast.SubmittedTx": {
            "type": "object",
            "properties": {
                "blockHash": {
                    "description": "BlockHash is the hash of the block where the transaction was included.",
                    "type": "string"
                },
                "blockHeight": {
                    "description": "BlockHeight is the height of the block where the transaction was included.",
                    "type": "integer"
                },
                "extraInfo": {
                    "description": "ExtraInfo provides extra information for given transaction.",
                    "type": "string"
                },
                "merklePath": {
                    "description": "MerklePath is the Merkle path used to calculate Merkle root of the block in which the transaction was included.",
                    "type": "string"
                },
                "status": {
                    "description": "Status is the status of the response.",
                    "type": "integer"
                },
                "timestamp": {
                    "description": "Timestamp is the timestamp of the block where the transaction was included.",
                    "type": "string"
                },
                "title": {
                    "description": "Title is the title of the response.",
                    "type": "string"
                },
                "txStatus": {
                    "description": "TxStatus is the status of the transaction.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/broadcast.TxStatus"
                        }
                    ]
                },
                "txid": {
                    "description": "TxID is the transaction id.",
                    "type": "string"
                }
            }
        },
        "broadcast.TxStatus": {
            "type": "string",
            "enum": [
                "UNKNOWN",
                "QUEUED",
                "RECEIVED",
                "STORED",
                "ANNOUNCED_TO_NETWORK",
                "REQUESTED_BY_NETWORK",
                "SENT_TO_NETWORK",
                "ACCEPTED_BY_NETWORK",
                "SEEN_ON_NETWORK",
                "MINED",
                "SEEN_IN_ORPHAN_MEMPOOL",
                "CONFIRMED",
                "REJECTED"
            ],
            "x-enum-comments": {
                "AcceptedByNetwork": "7",
                "AnnouncedToNetwork": "4",
                "Confirmed": "108",
                "Mined": "9",
                "Queued": "1",
                "Received": "2",
                "Rejected": "109",
                "RequestedByNetwork": "5",
                "SeenInOrphanMempool": "10",
                "SeenOnNetwork": "8",
                "SentToNetwork": "6",
                "Stored": "3",
                "Unknown": "0"
            },
            "x-enum-varnames": [
                "Unknown",
                "Queued",
                "Received",
                "Stored",
                "AnnouncedToNetwork",
                "RequestedByNetwork",
                "SentToNetwork",
                "AcceptedByNetwork",
                "SeenOnNetwork",
                "Mined",
                "SeenInOrphanMempool",
                "Confirmed",
                "Rejected"
            ]
        },
        "datastore.QueryParams": {
            "type": "object",
            "properties": {
                "order_by_field": {
                    "type": "string"
                },
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "sort_direction": {
                    "type": "string"
                }
            }
        },
        "destinations.CreateDestination": {
            "type": "object",
            "properties": {
                "metadata": {
                    "$ref": "#/definitions/engine.Metadata"
                }
            }
        },
        "destinations.UpdateDestination": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "locking_script": {
                    "type": "string"
                },
                "metadata": {
                    "$ref": "#/definitions/engine.Metadata"
                }
            }
        },
        "engine.Metadata": {
            "type": "object",
            "additionalProperties": true
        },
        "models.Destination": {
            "type": "object",
            "properties": {
                "address": {
                    "description": "Address is a destination's address.",
                    "type": "string"
                },
                "chain": {
                    "description": "Chain is a destination's chain representation.",
                    "type": "integer"
                },
                "created_at": {
                    "description": "CreatedAt is a time when outer model was created.",
                    "type": "string"
                },
                "deleted_at": {
                    "description": "DeletedAt is a time when outer model was deleted.",
                    "type": "string"
                },
                "draft_id": {
                    "description": "DraftID is a destination's draft id.",
                    "type": "string"
                },
                "id": {
                    "description": "ID is a destination id.",
                    "type": "string"
                },
                "locking_script": {
                    "description": "LockingScript is a destination's locking script.",
                    "type": "string"
                },
                "metadata": {
                    "description": "Metadata is a metadata map of outer model.",
                    "type": "object",
                    "additionalProperties": true
                },
                "monitor": {
                    "description": "Monitor is a time when destination was monitored.",
                    "type": "string"
                },
                "num": {
                    "description": "Num is a destination's num representation.",
                    "type": "integer"
                },
                "type": {
                    "description": "Type is a destination's type.",
                    "type": "string"
                },
                "updated_at": {
                    "description": "UpdatedAt is a time when outer model was updated.",
                    "type": "string"
                },
                "xpub_id": {
                    "description": "XpubID is a destination's xpub related id used to register destination.",
                    "type": "string"
                }
            }
        },
        "models.FeeUnit": {
            "type": "object",
            "properties": {
                "bytes": {
                    "description": "Bytes is a fee unit bytes representation.",
                    "type": "integer"
                },
                "satoshis": {
                    "description": "Satoshis is a fee unit satoshis amount.",
                    "type": "integer"
                }
            }
        },
        "models.MapProtocol": {
            "type": "object",
            "properties": {
                "app": {
                    "description": "App is a map protocol app.",
                    "type": "string"
                },
                "keys": {
                    "description": "Keys is a map protocol keys.",
                    "type": "object",
                    "additionalProperties": true
                },
                "type": {
                    "description": "Type is a map protocol type.",
                    "type": "string"
                }
            }
        },
        "models.OpReturn": {
            "type": "object",
            "properties": {
                "hex": {
                    "description": "Hex is a full hex of op return.",
                    "type": "string"
                },
                "hex_parts": {
                    "description": "HexParts is a slice of splitted hex parts.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "map": {
                    "description": "Map is a pointer to a map protocol object.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.MapProtocol"
                        }
                    ]
                },
                "string_parts": {
                    "description": "StringParts is a slice of string parts.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "models.PaymailP4": {
            "type": "object",
            "properties": {
                "alias": {
                    "description": "Alias is a paymail p4 alias.",
                    "type": "string"
                },
                "domain": {
                    "description": "Domain is a paymail p4 domain.",
                    "type": "string"
                },
                "from_paymail": {
                    "description": "FromPaymail is a paymail p4 from paymail.",
                    "type": "string"
                },
                "note": {
                    "description": "Note is a paymail p4 note.",
                    "type": "string"
                },
                "pub_key": {
                    "description": "PubKey is a paymail p4 pub key.",
                    "type": "string"
                },
                "receive_endpoint": {
                    "description": "ReceiveEndpoint is a paymail p4 receive endpoint.",
                    "type": "string"
                },
                "reference_id": {
                    "description": "ReferenceID is a paymail p4 reference id.",
                    "type": "string"
                },
                "resolution_type": {
                    "description": "ResolutionType is a paymail p4 resolution type.",
                    "type": "string"
                }
            }
        },
        "models.ScriptOutput": {
            "type": "object",
            "properties": {
                "address": {
                    "description": "Address is a script output address.",
                    "type": "string"
                },
                "satoshis": {
                    "description": "Satoshis is a script output satoshis.",
                    "type": "integer"
                },
                "script": {
                    "description": "Script is a script output script.",
                    "type": "string"
                },
                "script_type": {
                    "description": "ScriptType is a script output script type.",
                    "type": "string"
                }
            }
        },
        "models.SyncConfig": {
            "type": "object",
            "properties": {
                "broadcast": {
                    "description": "Broadcast is a flag that indicates whether to broadcast transaction or not.",
                    "type": "boolean"
                },
                "broadcast_instant": {
                    "description": "BroadcastInstant is a flag that indicates whether to broadcast transaction instantly or not.",
                    "type": "boolean"
                },
                "paymail_p2p": {
                    "description": "PaymailP2P is a flag that indicates whether to use paymail p2p or not.",
                    "type": "boolean"
                },
                "sync_on_chain": {
                    "description": "SyncOnChain is a flag that indicates whether to sync transaction on chain or not.",
                    "type": "boolean"
                }
            }
        },
        "models.Transaction": {
            "type": "object",
            "properties": {
                "block_hash": {
                    "description": "BlockHash is a block hash that transaction is in.",
                    "type": "string"
                },
                "block_height": {
                    "description": "BlockHeight is a block height that transaction is in.",
                    "type": "integer"
                },
                "created_at": {
                    "description": "CreatedAt is a time when outer model was created.",
                    "type": "string"
                },
                "deleted_at": {
                    "description": "DeletedAt is a time when outer model was deleted.",
                    "type": "string"
                },
                "direction": {
                    "description": "TransactionDirection is a transaction direction (inbound/outbound).",
                    "type": "string"
                },
                "draft_id": {
                    "description": "DraftID is a transaction related draft id.",
                    "type": "string"
                },
                "fee": {
                    "description": "Fee is a transaction fee.",
                    "type": "integer"
                },
                "hex": {
                    "description": "Hex is a transaction hex.",
                    "type": "string"
                },
                "id": {
                    "description": "ID is a transaction id.",
                    "type": "string"
                },
                "metadata": {
                    "description": "Metadata is a metadata map of outer model.",
                    "type": "object",
                    "additionalProperties": true
                },
                "number_of_inputs": {
                    "description": "NumberOfInputs is a number of transaction inputs.",
                    "type": "integer"
                },
                "number_of_outputs": {
                    "description": "NumberOfOutputs is a number of transaction outputs.",
                    "type": "integer"
                },
                "output_value": {
                    "description": "OutputValue is a total output value.",
                    "type": "integer"
                },
                "outputs": {
                    "description": "Outputs represents all spv-wallet-transaction outputs. Will be shown only for admin.",
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "status": {
                    "description": "Status is a transaction status.",
                    "type": "string"
                },
                "total_value": {
                    "description": "TotalValue is a total input value.",
                    "type": "integer"
                },
                "updated_at": {
                    "description": "UpdatedAt is a time when outer model was updated.",
                    "type": "string"
                },
                "xpub_in_ids": {
                    "description": "XpubInIDs is a slice of xpub input ids.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "xpub_out_ids": {
                    "description": "XpubOutIDs is a slice of xpub output ids.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "models.TransactionConfig": {
            "type": "object",
            "properties": {
                "change_destinations": {
                    "description": "ChangeDestinations is a slice of change destinations.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Destination"
                    }
                },
                "change_destinations_strategy": {
                    "description": "ChangeStrategy is a change strategy.",
                    "type": "string"
                },
                "change_minimum_satoshis": {
                    "description": "ChangeMinimumSatoshis is a minimum satoshis for change.",
                    "type": "integer"
                },
                "change_number_of_destinations": {
                    "description": "ChangeNumberOfDestinations is a number of change destinations.",
                    "type": "integer"
                },
                "change_satoshis": {
                    "description": "ChangeSatoshis is a change satoshis.",
                    "type": "integer"
                },
                "expires_in": {
                    "description": "ExpiresAt is a time when transaction expires.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/time.Duration"
                        }
                    ]
                },
                "fee": {
                    "description": "Fee is a fee amount.",
                    "type": "integer"
                },
                "fee_unit": {
                    "description": "FeeUnit is a pointer to a fee unit object.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.FeeUnit"
                        }
                    ]
                },
                "from_utxos": {
                    "description": "FromUtxos is a slice of from utxos used to build transaction.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.UtxoPointer"
                    }
                },
                "include_utxos": {
                    "description": "IncludeUtxos is a slice of utxos to include in transaction.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.UtxoPointer"
                    }
                },
                "inputs": {
                    "description": "Inputs is a slice of transaction inputs.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.TransactionInput"
                    }
                },
                "outputs": {
                    "description": "Outputs is a slice of transaction outputs.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.TransactionOutput"
                    }
                },
                "send_all_to": {
                    "description": "SendAllTo is a pointer to a transaction output object.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.TransactionOutput"
                        }
                    ]
                },
                "sync": {
                    "description": "Sync contains sync configuration.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.SyncConfig"
                        }
                    ]
                }
            }
        },
        "models.TransactionInput": {
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "CreatedAt is a time when outer model was created.",
                    "type": "string"
                },
                "deleted_at": {
                    "description": "DeletedAt is a time when outer model was deleted.",
                    "type": "string"
                },
                "destination": {
                    "description": "Destination is a pointer to a destination object.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.Destination"
                        }
                    ]
                },
                "draft_id": {
                    "description": "DraftID is a utxo transaction related draft id.",
                    "type": "string"
                },
                "id": {
                    "description": "ID is a utxo id.",
                    "type": "string"
                },
                "metadata": {
                    "description": "Metadata is a metadata map of outer model.",
                    "type": "object",
                    "additionalProperties": true
                },
                "output_index": {
                    "description": "OutputIndex is a output index that utxo points to.",
                    "type": "integer"
                },
                "reserved_at": {
                    "description": "ReservedAt is a time utxo was reserved at.",
                    "type": "string"
                },
                "satoshis": {
                    "description": "Satoshis is a utxo satoshis amount.",
                    "type": "integer"
                },
                "script_pub_key": {
                    "description": "ScriptPubKey is a utxo script pub key.",
                    "type": "string"
                },
                "spending_tx_id": {
                    "description": "SpendingTxID is a spending transaction id - null if not spent yet.",
                    "type": "string"
                },
                "transaction": {
                    "description": "Transaction is a transaction pointer that utxo points to.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.Transaction"
                        }
                    ]
                },
                "transaction_id": {
                    "description": "TransactionID is a transaction id that utxo points to.",
                    "type": "string"
                },
                "type": {
                    "description": "Type is a utxo type.",
                    "type": "string"
                },
                "updated_at": {
                    "description": "UpdatedAt is a time when outer model was updated.",
                    "type": "string"
                },
                "xpub_id": {
                    "description": "XpubID is a utxo related xpub id.",
                    "type": "string"
                }
            }
        },
        "models.TransactionOutput": {
            "type": "object",
            "properties": {
                "op_return": {
                    "description": "OpReturn is a pointer to a op return object.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.OpReturn"
                        }
                    ]
                },
                "paymail_p4": {
                    "description": "PaymailP4 is a pointer to a paymail p4 object.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.PaymailP4"
                        }
                    ]
                },
                "satoshis": {
                    "description": "Satoshis is a satoshis amount.",
                    "type": "integer"
                },
                "script": {
                    "description": "Script is a transaction output string representation of script.",
                    "type": "string"
                },
                "scripts": {
                    "description": "ScriptType is a transaction output script type.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ScriptOutput"
                    }
                },
                "to": {
                    "description": "To is a transaction output destination address.",
                    "type": "string"
                },
                "use_for_change": {
                    "description": "UseForChange is a flag that indicates if this output should be used for change.",
                    "type": "boolean"
                }
            }
        },
        "models.UtxoPointer": {
            "type": "object",
            "properties": {
                "output_index": {
                    "description": "OutputIndex is a output index that utxo points to.",
                    "type": "integer"
                },
                "transaction_id": {
                    "description": "TransactionID is a transaction id that utxo points to.",
                    "type": "string"
                }
            }
        },
        "time.Duration": {
            "type": "integer",
            "enum": [
                -9223372036854775808,
                9223372036854775807,
                1,
                1000,
                1000000,
                1000000000,
                60000000000,
                3600000000000,
                -9223372036854775808,
                9223372036854775807,
                1,
                1000,
                1000000,
                1000000000,
                60000000000,
                3600000000000,
                -9223372036854775808,
                9223372036854775807,
                1,
                1000,
                1000000,
                1000000000,
                60000000000,
                3600000000000
            ],
            "x-enum-varnames": [
                "minDuration",
                "maxDuration",
                "Nanosecond",
                "Microsecond",
                "Millisecond",
                "Second",
                "Minute",
                "Hour",
                "minDuration",
                "maxDuration",
                "Nanosecond",
                "Microsecond",
                "Millisecond",
                "Second",
                "Minute",
                "Hour",
                "minDuration",
                "maxDuration",
                "Nanosecond",
                "Microsecond",
                "Millisecond",
                "Second",
                "Minute",
                "Hour"
            ]
        },
        "transactions.NewTransaction": {
            "type": "object",
            "properties": {
                "config": {
                    "$ref": "#/definitions/models.TransactionConfig"
                },
                "metadata": {
                    "$ref": "#/definitions/engine.Metadata"
                }
            }
        },
        "transactions.UpdateTransaction": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "metadata": {
                    "$ref": "#/definitions/engine.Metadata"
                }
            }
        }
    },
    "securityDefinitions": {
        "callback-auth": {
            "type": "apiKey",
            "name": "authorization",
            "in": "header"
        },
        "x-auth-xpub": {
            "type": "apiKey",
            "name": "x-auth-xpub",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "v0.12.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "SPV Wallet",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
