// Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/access-key": {
            "get": {
                "security": [
                    {
                        "bux-auth-xpub": []
                    }
                ],
                "description": "Get access key",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Access-key"
                ],
                "summary": "Get access key",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "bux-auth-xpub": []
                    }
                ],
                "description": "Create access key",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Access-key"
                ],
                "summary": "Create access key",
                "parameters": [
                    {
                        "type": "string",
                        "description": "metadata",
                        "name": "metadata",
                        "in": "query"
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "bux-auth-xpub": []
                    }
                ],
                "description": "Revoke access key",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Access-key"
                ],
                "summary": "Revoke access key",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    }
                }
            }
        },
        "/v1/access-key/count": {
            "post": {
                "security": [
                    {
                        "bux-auth-xpub": []
                    }
                ],
                "description": "Count of access keys",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Access-key"
                ],
                "summary": "Count of access keys",
                "parameters": [
                    {
                        "type": "string",
                        "description": "metadata",
                        "name": "metadata",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "conditions",
                        "name": "conditions",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/access-key/search": {
            "post": {
                "security": [
                    {
                        "bux-auth-xpub": []
                    }
                ],
                "description": "Search access key",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Access-key"
                ],
                "summary": "Search access key",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page_size",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "order_by_field",
                        "name": "order_by_field",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "sort_direction",
                        "name": "sort_direction",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "metadata",
                        "name": "metadata",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "conditions",
                        "name": "conditions",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/admin/access-keys/count": {
            "post": {
                "security": [
                    {
                        "bux-auth-xpub": []
                    }
                ],
                "description": "Access Keys Count",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Access Keys Count",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Metadata filter",
                        "name": "metadata",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Conditions filter",
                        "name": "conditions",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/admin/access-keys/search": {
            "post": {
                "security": [
                    {
                        "bux-auth-xpub": []
                    }
                ],
                "description": "Access Keys Search",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Access Keys Search",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page_size",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "order_by_field",
                        "name": "order_by_field",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "sort_direction",
                        "name": "sort_direction",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Metadata filter",
                        "name": "metadata",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Conditions filter",
                        "name": "conditions",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/admin/block-headers/count": {
            "post": {
                "security": [
                    {
                        "bux-auth-xpub": []
                    }
                ],
                "description": "Get block headers count",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Get block headers count",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Metadata filter",
                        "name": "metadata",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Conditions filter",
                        "name": "conditions",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/admin/block-headers/search": {
            "post": {
                "security": [
                    {
                        "bux-auth-xpub": []
                    }
                ],
                "description": "Search for block headers",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Search for block headers",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page_size",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "order_by_field",
                        "name": "order_by_field",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "sort_direction",
                        "name": "sort_direction",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Metadata filter",
                        "name": "metadata",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Conditions filter",
                        "name": "conditions",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/admin/destinations/count": {
            "post": {
                "security": [
                    {
                        "bux-auth-xpub": []
                    }
                ],
                "description": "Count destinations",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Count destinations",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Metadata filter",
                        "name": "metadata",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Conditions filter",
                        "name": "conditions",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/admin/destinations/search": {
            "post": {
                "security": [
                    {
                        "bux-auth-xpub": []
                    }
                ],
                "description": "Search for destinations",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Search for destinations",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page_size",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "order_by_field",
                        "name": "order_by_field",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "sort_direction",
                        "name": "sort_direction",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Metadata filter",
                        "name": "metadata",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Conditions filter",
                        "name": "conditions",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/admin/paymail/create": {
            "post": {
                "security": [
                    {
                        "bux-auth-xpub": []
                    }
                ],
                "description": "Create paymail",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Create paymail",
                "parameters": [
                    {
                        "type": "string",
                        "description": "xpub",
                        "name": "xpub",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "address",
                        "name": "address",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "public_name",
                        "name": "public_name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "avatar",
                        "name": "avatar",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "metadata",
                        "name": "metadata",
                        "in": "query"
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    }
                }
            }
        },
        "/v1/admin/paymail/delete": {
            "delete": {
                "security": [
                    {
                        "bux-auth-xpub": []
                    }
                ],
                "description": "Delete paymail",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Delete paymail",
                "parameters": [
                    {
                        "type": "string",
                        "description": "address",
                        "name": "address",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/admin/paymail/get": {
            "get": {
                "security": [
                    {
                        "bux-auth-xpub": []
                    }
                ],
                "description": "Get paymail",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Get paymail",
                "parameters": [
                    {
                        "type": "string",
                        "description": "address",
                        "name": "address",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/admin/paymails/count": {
            "post": {
                "security": [
                    {
                        "bux-auth-xpub": []
                    }
                ],
                "description": "Paymail addresses count",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Paymail addresses count",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Metadata filter",
                        "name": "metadata",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Conditions filter",
                        "name": "conditions",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/admin/paymails/search": {
            "post": {
                "security": [
                    {
                        "bux-auth-xpub": []
                    }
                ],
                "description": "Paymail addresses search",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Paymail addresses search",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page_size",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "order_by_field",
                        "name": "order_by_field",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "sort_direction",
                        "name": "sort_direction",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Metadata filter",
                        "name": "metadata",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Conditions filter",
                        "name": "conditions",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/admin/stats": {
            "get": {
                "security": [
                    {
                        "bux-auth-xpub": []
                    }
                ],
                "description": "Get stats",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Get stats",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/admin/status": {
            "get": {
                "security": [
                    {
                        "bux-auth-xpub": []
                    }
                ],
                "description": "Get status",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Get status",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/admin/transactions/count": {
            "post": {
                "security": [
                    {
                        "bux-auth-xpub": []
                    }
                ],
                "description": "Count transactions",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Count transactions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Metadata filter",
                        "name": "metadata",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Conditions filter",
                        "name": "conditions",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/admin/transactions/record": {
            "post": {
                "security": [
                    {
                        "bux-auth-xpub": []
                    }
                ],
                "description": "Record transactions",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Record transactions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Transaction hex",
                        "name": "hex",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    }
                }
            }
        },
        "/v1/admin/transactions/search": {
            "post": {
                "security": [
                    {
                        "bux-auth-xpub": []
                    }
                ],
                "description": "Search for transactions",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Search for transactions",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page_size",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "order_by_field",
                        "name": "order_by_field",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "sort_direction",
                        "name": "sort_direction",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Metadata filter",
                        "name": "metadata",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Conditions filter",
                        "name": "conditions",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/admin/utxos/count": {
            "post": {
                "security": [
                    {
                        "bux-auth-xpub": []
                    }
                ],
                "description": "Count utxos",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Count utxos",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Metadata filter",
                        "name": "metadata",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Conditions filter",
                        "name": "conditions",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/admin/utxos/search": {
            "post": {
                "security": [
                    {
                        "bux-auth-xpub": []
                    }
                ],
                "description": "Search for utxos",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Search for utxos",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page_size",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "order_by_field",
                        "name": "order_by_field",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "sort_direction",
                        "name": "sort_direction",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Metadata filter",
                        "name": "metadata",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Conditions filter",
                        "name": "conditions",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/admin/xpubs/count": {
            "post": {
                "security": [
                    {
                        "bux-auth-xpub": []
                    }
                ],
                "description": "Count xpubs",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Count xpubs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Metadata filter",
                        "name": "metadata",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Conditions filter",
                        "name": "conditions",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/admin/xpubs/search": {
            "post": {
                "security": [
                    {
                        "bux-auth-xpub": []
                    }
                ],
                "description": "Search for xpubs",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Search for xpubs",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page_size",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "order_by_field",
                        "name": "order_by_field",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "sort_direction",
                        "name": "sort_direction",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Metadata filter",
                        "name": "metadata",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Conditions filter",
                        "name": "conditions",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/destination": {
            "get": {
                "security": [
                    {
                        "bux-auth-xpub": []
                    }
                ],
                "description": "Get a destination",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Destinations"
                ],
                "summary": "Get a destination",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Destination ID",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Destination address",
                        "name": "address",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Destination locking script",
                        "name": "locking_script",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "bux-auth-xpub": []
                    }
                ],
                "description": "Create a new destination",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Destinations"
                ],
                "summary": "Create a new destination",
                "parameters": [
                    {
                        "type": "string",
                        "description": "type",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "reference_id",
                        "name": "reference_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "metadata",
                        "name": "metadata",
                        "in": "query"
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "bux-auth-xpub": []
                    }
                ],
                "description": "Update destination",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Destinations"
                ],
                "summary": "Update destination",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Destination ID",
                        "name": "id",
                        "in": "path"
                    },
                    {
                        "type": "string",
                        "description": "Destination Address",
                        "name": "address",
                        "in": "path"
                    },
                    {
                        "type": "string",
                        "description": "Destination Locking Script",
                        "name": "locking_script",
                        "in": "path"
                    },
                    {
                        "description": "Destination Metadata",
                        "name": "metadata",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/destination/count": {
            "post": {
                "security": [
                    {
                        "bux-auth-xpub": []
                    }
                ],
                "description": "Count Destinations",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Destinations"
                ],
                "summary": "Count Destinations",
                "parameters": [
                    {
                        "type": "string",
                        "description": "metadata",
                        "name": "metadata",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "condition",
                        "name": "condition",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/destination/search": {
            "get": {
                "security": [
                    {
                        "bux-auth-xpub": []
                    }
                ],
                "description": "Search for a destination",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Destinations"
                ],
                "summary": "Search for a destination",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page_size",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "order_by_field",
                        "name": "order_by_field",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "sort_direction",
                        "name": "sort_direction",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "metadata",
                        "name": "metadata",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "condition",
                        "name": "condition",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/paymail": {
            "post": {
                "security": [
                    {
                        "bux-auth-xpub": []
                    }
                ],
                "description": "Create paymail",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Paymails"
                ],
                "summary": "Create paymail",
                "parameters": [
                    {
                        "type": "string",
                        "description": "key",
                        "name": "key",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "address",
                        "name": "address",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "public_name",
                        "name": "public_name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "avatar",
                        "name": "avatar",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "metadata",
                        "name": "metadata",
                        "in": "query"
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "bux-auth-xpub": []
                    }
                ],
                "description": "Delete paymail",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Paymails"
                ],
                "summary": "Delete paymail",
                "parameters": [
                    {
                        "type": "string",
                        "description": "address",
                        "name": "address",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/transaction": {
            "get": {
                "security": [
                    {
                        "bux-auth-xpub": []
                    }
                ],
                "description": "Get transaction by id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transactions"
                ],
                "summary": "Get transaction by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "bux-auth-xpub": []
                    }
                ],
                "description": "New transaction",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transactions"
                ],
                "summary": "New transaction",
                "parameters": [
                    {
                        "type": "string",
                        "description": "transaction config",
                        "name": "config",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "metadata",
                        "name": "metadata",
                        "in": "query"
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "bux-auth-xpub": []
                    }
                ],
                "description": "Update transaction",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transactions"
                ],
                "summary": "Update transaction",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "metadata",
                        "name": "metadata",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/transaction/callback": {
            "post": {
                "security": [
                    {
                        "callback-auth": []
                    }
                ],
                "tags": [
                    "Transactions"
                ],
                "summary": "Broadcast Callback",
                "parameters": [
                    {
                        "description": "transaction",
                        "name": "transaction",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/broadcast.SubmittedTx"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/transaction/count": {
            "post": {
                "security": [
                    {
                        "bux-auth-xpub": []
                    }
                ],
                "description": "Count of transactions",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transactions"
                ],
                "summary": "Count of transactions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "metadata",
                        "name": "metadata",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "conditions",
                        "name": "conditions",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/transaction/record": {
            "post": {
                "security": [
                    {
                        "bux-auth-xpub": []
                    }
                ],
                "description": "Record transaction",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transactions"
                ],
                "summary": "Record transaction",
                "parameters": [
                    {
                        "type": "string",
                        "description": "hex",
                        "name": "hex",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "reference_id",
                        "name": "reference_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "metadata",
                        "name": "metadata",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/transaction/search": {
            "post": {
                "security": [
                    {
                        "bux-auth-xpub": []
                    }
                ],
                "description": "Search transaction",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transactions"
                ],
                "summary": "Search transaction",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page_size",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "order_by_field",
                        "name": "order_by_field",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "sort_direction",
                        "name": "sort_direction",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "metadata",
                        "name": "metadata",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "conditions",
                        "name": "conditions",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/utxo": {
            "get": {
                "security": [
                    {
                        "bux-auth-xpub": []
                    }
                ],
                "description": "Get UTXO",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UTXO"
                ],
                "summary": "Get UTXO",
                "parameters": [
                    {
                        "type": "string",
                        "description": "tx_id",
                        "name": "tx_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "output_index",
                        "name": "output_index",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/utxo/count": {
            "post": {
                "security": [
                    {
                        "bux-auth-xpub": []
                    }
                ],
                "description": "Count of UTXOs",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UTXO"
                ],
                "summary": "Count of UTXOs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "metadata",
                        "name": "metadata",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "conditions",
                        "name": "conditions",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/utxo/search": {
            "post": {
                "security": [
                    {
                        "bux-auth-xpub": []
                    }
                ],
                "description": "Search UTXO",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UTXO"
                ],
                "summary": "Search UTXO",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page_size",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "order_by_field",
                        "name": "order_by_field",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "sort_direction",
                        "name": "sort_direction",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "metadata",
                        "name": "metadata",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "conditions",
                        "name": "conditions",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/utxo/unreserve": {
            "patch": {
                "security": [
                    {
                        "bux-auth-xpub": []
                    }
                ],
                "description": "Unreserve UTXOs",
                "tags": [
                    "UTXO"
                ],
                "summary": "Unreserve UTXOs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "draft tx id",
                        "name": "reference_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    }
                }
            }
        },
        "/v1/xpub": {
            "get": {
                "security": [
                    {
                        "bux-auth-xpub": []
                    }
                ],
                "description": "Get xPub",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "xPub"
                ],
                "summary": "Get xPub",
                "parameters": [
                    {
                        "type": "string",
                        "description": "key",
                        "name": "key",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "bux-auth-xpub": []
                    }
                ],
                "description": "Create xPub",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "xPub"
                ],
                "summary": "Create xPub",
                "parameters": [
                    {
                        "type": "string",
                        "description": "key",
                        "name": "key",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "metadata",
                        "name": "metadata",
                        "in": "query"
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "bux-auth-xpub": []
                    }
                ],
                "description": "Update xPub",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "xPub"
                ],
                "summary": "Update xPub",
                "parameters": [
                    {
                        "type": "string",
                        "description": "metadata",
                        "name": "metadata",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        }
    },
    "definitions": {
        "broadcast.SubmittedTx": {
            "type": "object",
            "properties": {
                "blockHash": {
                    "description": "BlockHash is the hash of the block where the transaction was included.",
                    "type": "string"
                },
                "blockHeight": {
                    "description": "BlockHeight is the height of the block where the transaction was included.",
                    "type": "integer"
                },
                "extraInfo": {
                    "description": "ExtraInfo provides extra information for given transaction.",
                    "type": "string"
                },
                "merklePath": {
                    "description": "MerklePath is the Merkle path used to calculate Merkle root of the block in which the transaction was included.",
                    "type": "string"
                },
                "status": {
                    "description": "Status is the status of the response.",
                    "type": "integer"
                },
                "timestamp": {
                    "description": "Timestamp is the timestamp of the block where the transaction was included.",
                    "type": "string"
                },
                "title": {
                    "description": "Title is the title of the response.",
                    "type": "string"
                },
                "txStatus": {
                    "description": "TxStatus is the status of the transaction.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/broadcast.TxStatus"
                        }
                    ]
                },
                "txid": {
                    "description": "TxID is the transaction id.",
                    "type": "string"
                }
            }
        },
        "broadcast.TxStatus": {
            "type": "string",
            "enum": [
                "UNKNOWN",
                "QUEUED",
                "RECEIVED",
                "STORED",
                "ANNOUNCED_TO_NETWORK",
                "REQUESTED_BY_NETWORK",
                "SENT_TO_NETWORK",
                "ACCEPTED_BY_NETWORK",
                "SEEN_ON_NETWORK",
                "MINED",
                "SEEN_IN_ORPHAN_MEMPOOL",
                "CONFIRMED",
                "REJECTED"
            ],
            "x-enum-comments": {
                "AcceptedByNetwork": "7",
                "AnnouncedToNetwork": "4",
                "Confirmed": "108",
                "Mined": "9",
                "Queued": "1",
                "Received": "2",
                "Rejected": "109",
                "RequestedByNetwork": "5",
                "SeenInOrphanMempool": "10",
                "SeenOnNetwork": "8",
                "SentToNetwork": "6",
                "Stored": "3",
                "Unknown": "0"
            },
            "x-enum-varnames": [
                "Unknown",
                "Queued",
                "Received",
                "Stored",
                "AnnouncedToNetwork",
                "RequestedByNetwork",
                "SentToNetwork",
                "AcceptedByNetwork",
                "SeenOnNetwork",
                "Mined",
                "SeenInOrphanMempool",
                "Confirmed",
                "Rejected"
            ]
        }
    },
    "securityDefinitions": {
        "bux-auth-xpub": {
            "type": "apiKey",
            "name": "bux-auth-xpub",
            "in": "header"
        },
        "callback-auth": {
            "type": "apiKey",
            "name": "authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "v0.12.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "BUX: Server",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
