// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

const (
	XPubAuthScopes = "XPubAuth.Scopes"
)

// ApiComponentsModelsSharedConfig Shared config
type ApiComponentsModelsSharedConfig struct {
	ExperimentalFeatures *map[string]bool `json:"experimentalFeatures,omitempty"`
	PaymailDomains       *[]string        `json:"paymailDomains,omitempty"`
}

// ApiComponentsResponsesSharedConfig Shared config
type ApiComponentsResponsesSharedConfig = ApiComponentsModelsSharedConfig
