// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"fmt"
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

const (
	SignatureAuthScopes = "SignatureAuth.Scopes"
)

// ExResponse defines model for ExResponse.
type ExResponse struct {
	Something string `json:"something"`
	XpubID    string `json:"xpubID"`
}

// GetTestapiParams defines parameters for GetTestapi.
type GetTestapiParams struct {
	Something string `form:"something" json:"something"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /admin/testapi)
	GetAdminTestapi(c *gin.Context)

	// (GET /testapi)
	GetTestapi(c *gin.Context, params GetTestapiParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetAdminTestapi operation middleware
func (siw *ServerInterfaceWrapper) GetAdminTestapi(c *gin.Context) {

	c.Set(SignatureAuthScopes, []string{"admin"})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAdminTestapi(c)
}

// GetTestapi operation middleware
func (siw *ServerInterfaceWrapper) GetTestapi(c *gin.Context) {

	var err error

	c.Set(SignatureAuthScopes, []string{"user"})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTestapiParams

	// ------------- Required query parameter "something" -------------

	if paramValue := c.Query("something"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument something is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "something", c.Request.URL.Query(), &params.Something)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter something: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTestapi(c, params)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/admin/testapi", wrapper.GetAdminTestapi)
	router.GET(options.BaseURL+"/testapi", wrapper.GetTestapi)
}
