name: "[Manual] Build Docker Images"
run-name: "Build docker image version ${{ inputs.version || github.ref_name }} from ref  ${{ github.ref_name }}"
permissions:
  contents: write
  packages: write

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version name to build, if not specified, then the name of the branch will be used'
        required: false
      registries:
        description: 'Docker registries to use'
        required: true
        default: 'dockerhub,aws'
        type: choice
        options:
          - 'dockerhub'
          - 'aws'
          - 'dockerhub,aws'

jobs:
  release_default:
    if: contains(inputs.registries, 'dockerhub')
    uses: bactions/workflows/.github/workflows/release-go-server.yml@main
    with:
      version: ${{ inputs.version || github.ref_name }}
      ref: ${{ github.ref }}
      cgo_enabled: true
      release_create: false
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  release_aws:
    if: contains(inputs.registries, 'aws')
    uses: bactions/workflows/.github/workflows/release-go-server.yml@main
    with:
      version: ${{ inputs.version || github.ref_name }}
      ref: ${{ github.ref }}
      cgo_enabled: true
      release_create: false
      docker_registry: public.ecr.aws
      docker_org: ${{ vars.SPV_AWS_DOCKER_ORG }}
    secrets:
      DOCKER_USERNAME: ${{ secrets.SPV_AWS_ACCESS_KEY_ID }}
      DOCKER_PASSWORD: ${{ secrets.SPV_AWS_SECRET_ACCESS_KEY }}
