# Make sure to check the documentation at http://goreleaser.com
# ---------------------------
# General
# ---------------------------
before:
  hooks:
    - make all
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^.github:'
      - '^.vscode:'
      - '^test:'

# ---------------------------
# Builder
# ---------------------------
build:
  skip: true

# ---------------------------
# GitHub Release
# ---------------------------
release:
  prerelease: true
  name_template: "Release v{{.Version}}"

# ---------------------------
# Announce
# ---------------------------
announce:

  # See more at: https://goreleaser.com/customization/announce/#slack
  slack:
    enabled: false
    message_template: '{{ .ProjectName }} {{ .Tag }} is out! Changelog: https://github.com/bitcoin-sv/{{ .ProjectName }}/releases/tag/{{ .Tag }}'
    channel: '#test_slack'
    # username: ''
    # icon_emoji: ''
    # icon_url: ''

  # See more at: https://goreleaser.com/customization/announce/#twitter
  twitter:
    enabled: false
    message_template: '{{ .ProjectName }} {{ .Tag }} is out!'

  # See more at: https://goreleaser.com/customization/announce/#discord
  discord:
    enabled: false
    message_template: '{{ .ProjectName }} {{ .Tag }} is out!'
    # Defaults to `GoReleaser`
    author: ''
    # Defaults to `3888754` - the grey-ish from goreleaser
    color: ''
    # Defaults to `https://goreleaser.com/static/avatar.png`
    icon_url: ''

  # See more at: https://goreleaser.com/customization/announce/#reddit
  reddit:
    enabled: false
    # Application ID for Reddit Application
    application_id: ""
    # Username for your Reddit account
    username: ""
    # Defaults to `{{ .GitURL }}/releases/tag/{{ .Tag }}`
    # url_template: 'https://github.com/bitcoin-sv/{{ .ProjectName }}/releases/tag/{{ .Tag }}'
    # Defaults to `{{ .ProjectName }} {{ .Tag }} is out!`
    title_template: '{{ .ProjectName }} {{ .Tag }} is out!'
